### PR TITLE
openblas: improve cross compilation support

### PR DESCRIPTION
**Pull request by amrox**
Specify library name and version:  **openblas/0.3.12** - **openblas/0.3.17**

Cross-compilation in the recipe was explictly disabled. However, the source repository does seem to support cross-compilation in general. 

An issue with the architecture detection prevented cross-compilation from x86_64 to arm64 from working correctly. This issue was fix in https://github.com/OpenMathLib/OpenBLAS/pull/4142. This ports the same fix to older versions of OpenBlas.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

File: recipes/openblas/all/conanfile.py [hunk 1]
```diff
@@ -53,7 +53,10 @@ def configure(self):
 
     def validate(self):
         if hasattr(self, "settings_build") and cross_building(self, skip_x64_x86=True):
-            raise ConanInvalidConfiguration("Cross-building not implemented")
+            self.output.warning("Cross-building has only been tested for x86_64 to armv8. Proceed with caution.")
```
Comment (samuel-emrys) [inline recipes/openblas/all/conanfile.py:56]:
```suggestion
            self.output.warning("Cross-building has only been tested for x86_64 to armv8. Proceed with caution.")
        if Version(self.version) < "0.3.12" and self.settings.arch == "armv8":
            raise ConanInvalidConfiguration("armv8 builds are not supported for versions less than 0.3.12")
```

**Comment by EstebanDugueperoux2** [comment]
Hello @amrox,

I'm interested by your PR, using debian:bullseye docker image I get error on build 0.3.10 release while it works with 0.3.26 release:

CMake Error at cmake/prebuild.cmake:529 (MESSAGE):
  Compiling getarch_2nd failed Change Dir:
  /root/.conan2/p/b/openb46fc3a72077e9/b/build/Release/getarch2_build/CMakeFiles/CMakeTmp


  

  Run Build Command(s):/usr/bin/gmake cmTC_d3ad4/fast && /usr/bin/gmake -f
  CMakeFiles/cmTC_d3ad4.dir/build.make CMakeFiles/cmTC_d3ad4.dir/build

  gmake[1]: Entering directory
  '/root/.conan2/p/b/openb46fc3a72077e9/b/build/Release/getarch2_build/CMakeFiles/CMakeTmp'


  Building C object CMakeFiles/cmTC_d3ad4.dir/getarch_2nd.c.o

  /usr/bin/cc -m64 -fPIE -march=native -DGEMM_MULTITHREAD_THRESHOLD=4
  -DNO_PARALLEL_MAKE=0
  -I"/root/.conan2/p/b/openb46fc3a72077e9/b/build/Release/getarch2_build"
  -I"/root/.conan2/p/b/openb46fc3a72077e9/b/src"
  -I"/root/.conan2/p/b/openb46fc3a72077e9/b/build/Release" -o
  CMakeFiles/cmTC_d3ad4.dir/getarch_2nd.c.o -c
  /root/.conan2/p/b/openb46fc3a72077e9/b/src/getarch_2nd.c

  /root/.conan2/p/b/openb46fc3a72077e9/b/src/getarch_2nd.c: In function
  ‘main’:

  /root/.conan2/p/b/openb46fc3a72077e9/b/src/getarch_2nd.c:14:35: error:
  ‘SGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function); did
  you mean ‘SHGEMM_DEFAULT_UNROLL_M’?

     14 |     printf("SGEMM_UNROLL_M=%d\n", SGEMM_DEFAULT_UNROLL_M);
        |                                   ^~~~~~~~~~~~~~~~~~~~~~
        |                                   SHGEMM_DEFAULT_UNROLL_M

  /root/.conan2/p/b/openb46fc3a72077e9/b/src/getarch_2nd.c:14:35: note: each
  undeclared identifier is reported only once for each function it appears in

  /root/.conan2/p/b/openb46fc3a72077e9/b/src/getarch_2nd.c:15:35: error:
  ‘SGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function); did
  you mean ‘QGEMM_DEFAULT_UNROLL_N’?

     15 |     printf("SGEMM_UNROLL_N=%d\n", SGEMM_DEFAULT_UNROLL_N);
        |                                   ^~~~~~~~~~~~~~~~~~~~~~
        |                                   QGEMM_DEFAULT_UNROLL_N

  /root/.conan2/p/b/openb46fc3a72077e9/b/src/getarch_2nd.c:16:35: error:
  ‘DGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function); did
  you mean ‘XGEMM_DEFAULT_UNROLL_M’?

     16 |     printf("DGEMM_UNROLL_M=%d\n", DGEMM_DEFAULT_UNROLL_M);
        |                                   ^~~~~~~~~~~~~~~~~~~~~~
        |                                   XGEMM_DEFAULT_UNROLL_M

  /root/.conan2/p/b/openb46fc3a72077e9/b/src/getarch_2nd.c:17:35: error:
  ‘DGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function); did
  you mean ‘QGEMM_DEFAULT_UNROLL_N’?

     17 |     printf("DGEMM_UNROLL_N=%d\n", DGEMM_DEFAULT_UNROLL_N);
        |                                   ^~~~~~~~~~~~~~~~~~~~~~
        |                                   QGEMM_DEFAULT_UNROLL_N

  /root/.conan2/p/b/openb46fc3a72077e9/b/src/getarch_2nd.c:21:35: error:
  ‘CGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function); did
  you mean ‘XGEMM_DEFAULT_UNROLL_M’?

     21 |     printf("CGEMM_UNROLL_M=%d\n", CGEMM_DEFAULT_UNROLL_M);
        |                                   ^~~~~~~~~~~~~~~~~~~~~~
        |                                   XGEMM_DEFAULT_UNROLL_M

  /root/.conan2/p/b/openb46fc3a72077e9/b/src/getarch_2nd.c:22:35: error:
  ‘CGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function); did
  you mean ‘QGEMM_DEFAULT_UNROLL_N’?

     22 |     printf("CGEMM_UNROLL_N=%d\n", CGEMM_DEFAULT_UNROLL_N);
        |                                   ^~~~~~~~~~~~~~~~~~~~~~
        |                                   QGEMM_DEFAULT_UNROLL_N

  /root/.conan2/p/b/openb46fc3a72077e9/b/src/getarch_2nd.c:23:35: error:
  ‘ZGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function); did
  you mean ‘XGEMM_DEFAULT_UNROLL_M’?

     23 |     printf("ZGEMM_UNROLL_M=%d\n", ZGEMM_DEFAULT_UNROLL_M);
        |                                   ^~~~~~~~~~~~~~~~~~~~~~
        |                                   XGEMM_DEFAULT_UNROLL_M

  /root/.conan2/p/b/openb46fc3a72077e9/b/src/getarch_2nd.c:24:35: error:
  ‘ZGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function); did
  you mean ‘QGEMM_DEFAULT_UNROLL_N’?

     24 |     printf("ZGEMM_UNROLL_N=%d\n", ZGEMM_DEFAULT_UNROLL_N);
        |                                   ^~~~~~~~~~~~~~~~~~~~~~
        |                                   QGEMM_DEFAULT_UNROLL_N

  /root/.conan2/p/b/openb46fc3a72077e9/b/src/getarch_2nd.c:71:50: error:
  ‘SGEMM_DEFAULT_Q’ undeclared (first use in this function); did you mean
  ‘SHGEMM_DEFAULT_Q’?

     71 |     printf("#define SLOCAL_BUFFER_SIZE\t%ld\n", (SGEMM_DEFAULT_Q * SGEMM_DEFAULT_UNROLL_N * 4 * 1 *  sizeof(float)));
        |                                                  ^~~~~~~~~~~~~~~
        |                                                  SHGEMM_DEFAULT_Q

  /root/.conan2/p/b/openb46fc3a72077e9/b/src/getarch_2nd.c:72:50: error:
  ‘DGEMM_DEFAULT_Q’ undeclared (first use in this function); did you mean
  ‘SHGEMM_DEFAULT_Q’?

     72 |     printf("#define DLOCAL_BUFFER_SIZE\t%ld\n", (DGEMM_DEFAULT_Q * DGEMM_DEFAULT_UNROLL_N * 2 * 1 *  sizeof(double)));
        |                                                  ^~~~~~~~~~~~~~~
        |                                                  SHGEMM_DEFAULT_Q

  /root/.conan2/p/b/openb46fc3a72077e9/b/src/getarch_2nd.c:73:50: error:
  ‘CGEMM_DEFAULT_Q’ undeclared (first use in this function); did you mean
  ‘SHGEMM_DEFAULT_Q’?

     73 |     printf("#define CLOCAL_BUFFER_SIZE\t%ld\n", (CGEMM_DEFAULT_Q * CGEMM_DEFAULT_UNROLL_N * 4 * 2 *  sizeof(float)));
        |                                                  ^~~~~~~~~~~~~~~
        |                                                  SHGEMM_DEFAULT_Q

  /root/.conan2/p/b/openb46fc3a72077e9/b/src/getarch_2nd.c:74:50: error:
  ‘ZGEMM_DEFAULT_Q’ undeclared (first use in this function); did you mean
  ‘SHGEMM_DEFAULT_Q’?

     74 |     printf("#define ZLOCAL_BUFFER_SIZE\t%ld\n", (ZGEMM_DEFAULT_Q * ZGEMM_DEFAULT_UNROLL_N * 2 * 2 *  sizeof(double)));
        |                                                  ^~~~~~~~~~~~~~~
        |                                                  SHGEMM_DEFAULT_Q

  gmake[1]: *** [CMakeFiles/cmTC_d3ad4.dir/build.make:85:
  CMakeFiles/cmTC_d3ad4.dir/getarch_2nd.c.o] Error 1

  gmake[1]: Leaving directory
  '/root/.conan2/p/b/openb46fc3a72077e9/b/build/Release/getarch2_build/CMakeFiles/CMakeTmp'


  gmake: *** [Makefile:140: cmTC_d3ad4/fast] Error 2

  

Call Stack (most recent call first):
  cmake/system.cmake:157 (include)
  CMakeLists.txt:69 (include)


-- Configuring incomplete, errors occurred!
See also "/root/.conan2/p/b/openb46fc3a72077e9/b/build/Release/CMakeFiles/CMakeOutput.log".

openblas/0.3.10: ERROR: 
Package '2b7b4d8cb3a6f178c69b39cee6dde5a1d81a0aa6' build failed
openblas/0.3.10: WARN: Build folder /root/.conan2/p/b/openb46fc3a72077e9/b/build/Release
ERROR: openblas/0.3.10: Error in build() method, line 160
	cmake = self._configure_cmake()
while calling '_configure_cmake', line 92
	cmake.configure()
	ConanException: Error 1 while executing

perhaps we can drop 0.3.10 old release?

Regards.

**Comment by jcar87** [comment]
superseded by https://github.com/conan-io/conan-center-index/pull/24171 - please reopen (or open a new issue) if something is missing, thank you!
