### PR TITLE
libsystemd: Include libudev

### PR DESCRIPTION
**Pull request by jwillikers**
Specify library name and version:  **libsystemd/***

Include the udev library as a component of the libsystemd package.
Update Meson version.
Add `provides = "libudev"` to allow other providers of the `libudev` library, i.e. `eudev`.
It seems like the `provides` should be related to the `libudev` component instead of the entire package.
Is this possible?

I wasn't sure whether to add a separate package for libudev, i.e. something under `libudev/all`, or to include it as part of the libsystemd package.
In light of the fact that a separate package requires more resources to maintain, I opted for including it in the libsystemd package.
This will require only updating one package in CCI instead of two, at the cost of flexibility for managing libudev and libsystemd in distinct ways, i.e. trying to build one shared and the other static.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by RubenRBS** [comment]
> It seems like the provides should be related to the libudev component instead of the entire package.
Is this possible?

Not as far as I know, no. I've added this recipe to our next team review meeting, will let you

**Comment by jwillikers** [comment]
Looks like it is most likely a compiler bug causing the compilation error and not an actual issue with the project. I wonder if it's the version of GCC 9 in CI causing problems.

**Comment by jwillikers** [comment]
Yep, works with GCC 9.4. I'll add a workaround similar to Qt 6.

File: recipes/libsystemd/all/conanfile.py [hunk 1]
```diff
@@ -68,9 +69,17 @@ def requirements(self):
     def validate(self):
         if self.settings.os != "Linux":
             raise ConanInvalidConfiguration("Only Linux supported")
+        if os.getenv('NOT_ON_C3I', '0') == '0' and Version(self.version) >= "253.10" and self.settings.compiler == "gcc" and Version(self.settings.compiler.version) == "9":
```
Comment (uilianries) [inline recipes/libsystemd/all/conanfile.py:72]: I would suggest using config instead, much safer than env vars, and be customized by package. It could be `user.c3i.skip:libsystemd=True`, so in case needing this workaround again (IIRC we already used it in the past) we just add a new package name, or a wild card like `*`.


https://docs.conan.io/2/reference/config_files/global_conf.html

Comment (jwillikers) [reply recipes/libsystemd/all/conanfile.py:72]: That sounds great to me!

Comment (jwillikers) [reply recipes/libsystemd/all/conanfile.py]: Done.

**Review by valgur — APPROVED** [review]

**Comment by jwillikers** [comment]
This PR is necessary for #20358, which requires a newer version of `libudev` than is available in CI.
