### ISSUE TITLE
[package] cmake/3.x.x Does not work with Conan 2.0 due to multiple issues

### ISSUE THREAD

**Issue by System-Arch** [conan-io/conan-center-index#13613]
### Description

Attempting to build CMake with the current CCI recipe results in the following errors due to multiple compatibility issues:

> Exporting the recipe
> ERROR: Error loading conanfile at '/local/cmake/conanfile.py': Unable to load conanfile in /local/cmake/conanfile.py
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/local/cmake/conanfile.py", line 5, in <module>
>     from conans import tools, AutoToolsBuildEnvironment, CMake
> ImportError: cannot import name 'tools' from 'conans' (/mathworks/devel/sandbox/marc/conan-2.0/conan-io/conans/__init__.py)

### Package and Environment Details

* Package Name/Version: **cmake/3.24.2**
* Operating System+version: **Debian 10.3**
* Compiler+version: **GCC 8**
* Conan version: **conan 2.0.0.0beta4**
* Python version: **Python 3.7.3**

### Conan profile

-------- Input profiles --------
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux

### Steps to reproduce

conan-2.0 create . --version 3.24.2

### Logs

<details><summary>Click to expand log</summary>

```
Exporting the recipe
ERROR: Error loading conanfile at '/local/cmake/conanfile.py': Unable to load conanfile in /local/cmake/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/local/cmake/conanfile.py", line 5, in <module>
    from conans import tools, AutoToolsBuildEnvironment, CMake
ImportError: cannot import name 'tools' from 'conans' (/mathworks/devel/sandbox/marc/conan-2.0/conan-io/conans/__init__.py)
```

</details>

**Comment by System-Arch** [comment]
I have proposed fixes for these issues that I will submit as pull request.

**Comment by AndreyMlashkin** [comment]
don't forget to add "relates to https://github.com/conan-io/conan-center-index/issues/13613"
in the PR
