### PR TITLE
Automake: drop old version and recipe fixes

### LINKED ISSUE #15022: [package] automake/1.16.5 does not work with Conan 2.0
### Description

@jellespijker started a Conan 2.0 port of automake (see PR #12898) but had limited time to work on it and suggested that others could pick up this work. This issue covers my efforts to get automake working with Conan 2.0 building on previous efforts for autoconf (see #14860) and conversations with @memsharded (see https://github.com/conan-io/conan/issues/12785 and https://github.com/conan-io/conan/issues/12812)

### Package and Environment Details

* Package Name/Version: **automake/1.16.5**
* Operating System+version: **Windows 10**
* Compiler+version: **Visual Studio 2019**
* Conan version: **conan 2.0.0-dev** (with pending beta8 fixes)
* Python version: **Python 3.7.9**

### Conan profile

Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows
[tool_requires]
!openssl*: cmake/3.24.2

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows
[tool_requires]
!openssl*: cmake/3.24.2

### Steps to reproduce

conan-2.0 source --name automake --version 1.16.5 .

### Logs

<details><summary>Click to expand log</summary>

```
conan-2.0 source --name automake --version 1.16.5 .
ERROR: Error loading conanfile at 'C:\Users\marc\AppData\Local\Temp\tmp.rbe7dcCoKs\automake\conanfile.py': Unable to load conanfile in C:\Users\marc\AppData\Local\Temp\tmp.rbe7dcCoKs\automake\conanfile.py
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\marc\AppData\Local\Temp\tmp.rbe7dcCoKs\automake\conanfile.py", line 1, in <module>
    from conans import AutoToolsBuildEnvironment, ConanFile, tools
ImportError: cannot import name 'AutoToolsBuildEnvironment' from 'conans' (l:\conan-2.0\conan-io\conans\__init__.py)

ERROR: Conan-2.0 source failed for 'automake'
```

</details>

### PR DESCRIPTION
**Pull request by System-Arch**
Specify library name and version:  **automake/1.16.5**

This pull request started out building on the work of @jellespijker in PR #12898 and is an effort to close #15022.  PRs #15245 and #15358 have subsumed/augmented most of this effort. This PR is now reduced to dropping support for the unused 1.16.1 version.

---

- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by jellespijker** [comment]
@System-Arch thanks for picking up my slack, give a shout if you need some help

**Comment by System-Arch** [comment]
Hi @jcar87,
Thanks for all of your efforts to modernize the automake recipe and get it working with Conan 2.0. I've revised this PR to just encompass a few possible follow-on refinements. These include:

1. Dropped support for 1.16.1 as a grep shows no CCI clients using that version. There's only only one consumer of 1.16.2, so cleaning up that client and dropping 1.16.2 could be added if you concur.
2. Added annotations to conandata.yml per lint warnings
3. Tweaked win_bash logic in conanfile.py as I believe we need win_bash even if tools.microsoft.bash:path is set (unless Conan is now doing that for us)
4. Moved a couple of properties closer to package() method and added comment that they are only valid in that context.
5. Tweaked test_package/conanfile.py so that it passes with Conan 2.0 (needed extra requirement).

Please let me know what you think of these proposed changes. Thanks

**Comment by paulharris** [comment]
The existing automake recipe doesn't build on my Windows environment,
but this recipe version does!

I've tested this on my Windows environment, and the package builds for MSVC from within both the DOS shell and my msys shell.

Awesome work!

**Comment by paulharris** [comment]
The current libffi recipe (rrev 8f80c5) doesn't build with this automake.

```
ERROR: libffi/3.4.3: Error in generate() method, line 125
        ar_wrapper = unix_path(self, os.path.join(self.dependencies.direct_build['automake'].cpp_info.resdirs[0], f"automake-{automake_version}", "ar-lib"))
        IndexError: list index out of range
```

**Comment by StellaSmith** [comment]
> The current libffi recipe (rrev 8f80c5) doesn't build with this automake.
> 
> ```
> ERROR: libffi/3.4.3: Error in generate() method, line 125
>         ar_wrapper = unix_path(self, os.path.join(self.dependencies.direct_build['automake'].cpp_info.resdirs[0], f"automake-{automake_version}", "ar-lib"))
>         IndexError: list index out of range
> ```
Either the libffi recipe would have to use `ar_wrapper = self.dependencies.direct_build["automake"].conf_info.get("user.automake:lib-wrapper")`, or add `self.cpp_info.resdirs = [self._datarootdir]` to this recipe.

**Review by StellaSmith — DISMISSED** [review]

File: recipes/automake/all/test_package/conanfile.py [hunk 1]
```diff
@@ -40,6 +40,7 @@ def _settings_build(self):
 
     def build_requirements(self):
         self.build_requires(self.tested_reference_str)
+        self.tool_requires("autoconf/2.71") # Needed for autoreconf
```
Comment (jcar87) [inline recipes/automake/all/test_package/conanfile.py:43]: In my testing, this was not necessary since `automake` lists `autoconf` as a requirement (https://github.com/conan-io/conan-center-index/blob/7eba669c781b0d0e445c35abc025e0a7791248a5/recipes/automake/all/conanfile.py#L37-L38) 

is that not the case?
Happy to test this - it may be a case of a missing package_type somewhere, but the intention is that the downstream consumers don't need to specify this (it also doesnt hurt).

**Review by jcar87 — CHANGES_REQUESTED** [review]
Just need some clarification on a line, everything else is 🆗  :D

File: recipes/automake/all/test_package/conanfile.py (hunk 1 above)
Comment (System-Arch) [reply recipes/automake/all/test_package/conanfile.py:43]: Hi @jcar87,
Indeed in my latest testing it does not seem to be needed so I will remove it. Thanks

P.S. I believe I am testing with autoconf configured as an "application" per #14925

**Review by StellaSmith — APPROVED** [review]

File: recipes/automake/all/conanfile.py [hunk 2]
```diff
@@ -7,7 +7,7 @@
 from conan.tools.layout import basic_layout
 from conan.tools.scm import Version
 
-required_conan_version = ">=1.53.0"
+required_conan_version = ">=1.55.0"
```
Comment (SpaceIm) [inline recipes/automake/all/conanfile.py:10]: why?

Comment (System-Arch) [reply recipes/automake/all/conanfile.py:10]: Hi @Spacelm,
No, it's not strictly necessary, but it is a convenient field to touch to get the CI to re-run when it gets stuck. Also, specifying an older version than what the CI is running with means that there is no guarantee that the change will work with the specified version.
And yes, the other changes were subsumed/augmented in an overlapping change. I've updated the description to the current status. Thanks

Comment (prince-chrismc) [reply recipes/automake/all/conanfile.py:10]: min version is a nice to have, dropping older version is allowed, and optional patches should not have been there... all of that sounds totally acceptable :)

**Review by prince-chrismc — DISMISSED** [review]

**Review by ericLemanissier — DISMISSED** [review]

File: recipes/automake/all/conanfile.py (hunk 2 above)
Comment (SpaceIm) [reply recipes/automake/all/conanfile.py:10]: I just say this PR is not anymore about conan 2.0 compatibility. And I disagree with changing min conan version, specially when we know it was totally fine.

**Review by prince-chrismc — APPROVED** [review]

**Review by jcar87 — APPROVED** [review]
