### ISSUE TITLE
[package] breakpad/cci.20210521: Compilation error with gcc 11

### ISSUE THREAD

**Issue by artem-ogre** [conan-io/conan-center-index#18137]
### Description

Fails to compile with gcc 11 on Ubuntu 22.04:
```cxx
exception_handler.cc:141:49: error: no matching function for call to ‘max(int, long int)’
polaris-jammy                |   141 |   static const unsigned kSigStackSize = std::max(16384, SIGSTKSZ);
polaris-jammy                |       |                                         ~~~~~~~~^~~~~~~~~~~~~~~~~

```

### Package and Environment Details

* Package Name/Version: **breakpad/cci.20210521**
* Operating System+version: **Linux Ubuntu 22.04**
* Compiler+version: **GCC 11**

### Conan profile

[settings]
os=Linux
arch=x64
compiler=gcc
compiler.version=111
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

conan install -r conancenter breakpad/cci.20210521

### Logs

-
