### ISSUE TITLE
[gdk-pixbuf] <gdkpixbuf>/<2.42.8>: Fails to build on MSVC with glib/2.73.3

### ISSUE THREAD

**Issue by planetmarshall** [conan-io/conan-center-index#12342]
### Package and Environment Details

* Package Name/Version: **gdk-pixbuf/2.42.8**
* Operating System+version: **Windows 11**
* Compiler+version: **Visual Studio 2022**
* Conan version: **conan 1.52.1**
* Python version: **Python 3.8.10**

### Conan profile

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=17
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

Modify `gdk-pixbuf/all/conanfile.py` to require `glib/2.73.3`

```
cd gdk-pixbuf/all
conan create . gdk-pixbuf/2.42.8
```

Fails during linking with

```
 Linking target gdk-pixbuf/gdk_pixbuf-2.0-0.dll
FAILED: gdk-pixbuf/gdk_pixbuf-2.0-0.dll
"link" @gdk-pixbuf/gdk_pixbuf-2.0-0.dll.rsp
   Creating library gdk-pixbuf\gdk_pixbuf-2.0.lib and object gdk-pixbuf\gdk_pixbuf-2.0.exp
gdk-pixbuf-util.c.obj : error LNK2019: unresolved external symbol __imp_g_libintl_bindtextdomain referenced in function _gdk_pixbuf_init_gettext
libstaticpixbufloader-qtif.a(io-qtif.c.obj) : error LNK2019: unresolved external symbol __imp_g_libintl_ngettext referenced in function gdk_pixbuf__qtif_image_load
gdk-pixbuf\gdk_pixbuf-2.0-0.dll : fatal error LNK1120: 2 unresolved externals
```

I believe this may be related to this change in glib 2.73.1:

https://gitlab.gnome.org/GNOME/glib/-/commit/26435b570f0f55620cc7048f8ee718cce5f90734

I have tried linking with `libgettext` but so far unsuccessful

**Comment by planetmarshall** [comment]
Looks like fixed by #12331

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.

I'm closing this issue as this recipe has suffer plenty of modifications since this issue was reported and it seems to be already addressed.
If for some reason the problem remains nowadays, do not hesitate to reopen this issue or create a new ticket with updated information, preferably using `conan v2`.

Happy coding 🐸
