### PR TITLE
[libsystemd] Add version 261.2

### LINKED ISSUE #30420: [package] libsystemd/255.10: Unable to build with glibc-2.43
### Description

Unable to compile this recipe because there were added new errno in kernel headers. There is fix in libsystemd repo already, maybe we can add patch to recipe too?

https://github.com/systemd/systemd/commit/3cfb16998808a6ec8012a6120d0a82f0e1a0c8bb

Also the same on embedded forums

 https://lists.openembedded.org/g/openembedded-core/topic/whinlatter_patch_7_7/118580471

### Package and Environment Details

* Package Name/Version: **libsystemd/255.10**
* Operating System+version: **Linux OpenSUSE Tumbleweed**
* Compiler+version: **GCC 15.2**
* Conan version: **2.28.1**
* Python version: **Python 3.13.13**

### Conan profile

[settings]
arch=x86_64
build_type=RelWithDebInfo
compiler=gcc
compiler.cppstd=20
compiler.cstd=gnu23
compiler.libcxx=libstdc++11
compiler.version=15
os=Linux
[conf]
tools.build:compiler_executables={'c': 'gcc', 'cpp': 'g++'}

### Steps to reproduce

`conan install --requires=libsystemd/255.10 --build=missing`

### Logs

<details><summary>Click to expand log</summary>

```
src/basic/errno-to-name.h:71:23: error: initialized field overwritten [-Werror=override-init]
   71 |         [EFSBADCRC] = "EFSBADCRC",
      |                       ^~~~~~~~~~~
src/basic/errno-to-name.h:71:23: note: (near initialization for ?errno_names[74]?)
src/basic/errno-to-name.h:114:26: error: initialized field overwritten [-Werror=override-init]
  114 |         [EFSCORRUPTED] = "EFSCORRUPTED",
```

</details>

### PR DESCRIPTION
**Pull request by uilianries**
Changes to recipe:  **libsystemd/261.2**

#### Motivation

Issue #30420 points out a limitation in libsystemd that was already fixed in version 260. This PR brings the latest stable version of that project and includes the upstream fix.

#### Details

* The patch `0001-Remove-dependency-from-coreutils.patch` is a reflect of `251.18/0001-Remove-dependency-from-coreutils.patch`
* A bunch of options moved from boolean values (true, false) to enabled, disabled (you can see in the build log
* The build target version.h is now version
* Built locally on Linux:
  * [systemd-261.2-linux-amd64-gcc13-release-shared.log](https://github.com/user-attachments/files/31508712/systemd-261.2-linux-amd64-gcc13-release-shared.log)
  * [systemd-261.2-linux-amd64-gcc13-release-static.log](https://github.com/user-attachments/files/31508717/systemd-261.2-linux-amd64-gcc13-release-static.log)
* I did not remove old version logic as libsystemd is used by other recipes: libseat, grpc, dbus, zyre, czmq, zyre

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] If this is a bug fix, please link related issue or provide bug details
- [x] Tested locally with at least one configuration using a recent version of Conan

---
Add a :+1: reaction to pull requests you find [important](https://github.com/conan-io/conan-center-index/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc) to help the team prioritize, thanks!

### CODE REVIEW

**Comment by uilianries** [comment]
Build error reported via https://github.com/systemd/systemd/issues/43575
