### PR TITLE
fix building of qt5 with clang 13

### LINKED ISSUE #7942: qt/5.15.2: fails to build on macOS 12.0.1 Monterrey
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: qt/5.15.2
  * Operating System+version: macOS 12.0.1
  * Compiler+version: clang 13
  * Conan version: 1.42.0
  * Python version: 3.9.7

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Macos
os_build=Macos
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13.0
build_type=Release
arch=x86_64
arch_build=x86_64
[options]
[conf]
[build_requires]
[env]
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
compiling ~/.conan/data/qt/5.15.2/_/_/source/qt5/qtbase/src/plugins/platforms/cocoa/qcocoasessionmanager.cpp
In file included from ~/.conan/data/qt/5.15.2/_/_/source/qt5/qtbase/src/plugins/platforms/cocoa/qiosurfacegraphicsbuffer.mm:40:
~/.conan/data/qt/5.15.2/_/_/source/qt5/qtbase/src/plugins/platforms/cocoa/qiosurfacegraphicsbuffer.h:54:32: error: unknown type name 'CGColorSpaceRef'; did you mean 'QColorSpace'?
    void setColorSpace(QCFType<CGColorSpaceRef> colorSpace);
                               ^~~~~~~~~~~~~~~
                               QColorSpace
~/conan/data/qt/5.15.2/_/_/source/qt5/qtbase/include/QtCore/../../src/corelib/kernel/qmetatype.h:2090:1: note: 'QColorSpace' declared here
QT_FOR_EACH_STATIC_GUI_CLASS(QT_FORWARD_DECLARE_STATIC_TYPES_ITER)
^
~/.conan/data/qt/5.15.2/_/_/source/qt5/qtbase/include/QtCore/../../src/corelib/kernel/qmetatype.h:178:24: note: expanded from macro 'QT_FOR_EACH_STATIC_GUI_CLASS'
    F(QColorSpace, 87, QColorSpace) \
                       ^
~/.conan/data/qt/5.15.2/_/_/source/qt5/qtbase/src/plugins/platforms/cocoa/qiosurfacegraphicsbuffer.mm:90:32: error: out-of-line definition of 'setColorSpace' does not match any declaration in 'QIOSurfaceGraphicsBuffer'
void QIOSurfaceGraphicsBuffer::setColorSpace(QCFType<CGColorSpaceRef> colorSpace)
                               ^~~~~~~~~~~~~
~/.conan/data/qt/5.15.2/_/_/source/qt5/qtbase/src/plugins/platforms/cocoa/qiosurfacegraphicsbuffer.h:54:24: note: type of 1st parameter of member declaration does not match definition ('QCFType<QColorSpace>' vs 'QCFType<CGColorSpaceRef>')
    void setColorSpace(QCFType<CGColorSpaceRef> colorSpace);
                       ^
2 errors generated.

```

</details>

### PR DESCRIPTION
**Pull request by lkotsonis**
Specify library name and version:  **qt/5.x.x**

Fixes #7942 

---

- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [x] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
Thanks!

**Review by ericLemanissier — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
