### ISSUE TITLE
[package] libpq/16.8: Fails to build on macOS with latest Xcode

### ISSUE THREAD

**Issue by neobrain** [conan-io/conan-center-index#27681]
### Description

libpq builds with `-Werror` by default, which breaks the libpq build on my system (macOS 15.5). (Notably this breaks the Qt build, which pulls in libpq by default.)

Error log:
```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Werror=unguarded-availability-new -Wendif-labels -Wmissing-format-attribute -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-deprecated-non-prototype -Wno-format-truncation  -fPIC -O3 -pthread -D_REENTRANT -D_THREAD_SAFE -I../../src/port -DFRONTEND -I../../src/include -I/Users/tony/.conan2/p/b/libpqba409d4d294e2/b/src/src/include  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk  -DNDEBUG   -c -o thread.o /Users/tony/.conan2/p/b/libpqba409d4d294e2/b/src/src/port/thread.c
/Users/tony/.conan2/p/b/libpqba409d4d294e2/b/src/src/port/snprintf.c:424:27: error: 'strchrnul' is only available on macOS 15.4 or newer [-Werror,-Wunguarded-availability-new]
  424 |                         const char *next_pct = strchrnul(format + 1, '%');
      |                                                ^~~~~~~~~
/Users/tony/.conan2/p/b/libpqba409d4d294e2/b/src/src/port/snprintf.c:376:14: note: 'strchrnul' has been marked as being introduced in macOS 15.4 here, but the deployment target is macOS 15.0.0
  376 | extern char *strchrnul(const char *s, int c);
      |              ^
/Users/tony/.conan2/p/b/libpqba409d4d294e2/b/src/src/port/snprintf.c:424:27: note: enclose 'strchrnul' in a __builtin_available check to silence this warning
  424 |                         const char *next_pct = strchrnul(format + 1, '%');
      |                                                ^~~~~~~~~
  425 | 
  426 |                         /* Dump literal data we just scanned over */
  427 |                         dostr(format, next_pct - format, target);
  428 |                         if (target->failed)
  429 |                                 break;
  430 | 
  431 |                         if (*next_pct == '\0')
  432 |                                 break;
  433 |                         format = next_pct;
      |                                           
1 error generated.
```

If possible, the easiest solution might be to disable `-Werror` for this package.

### Package and Environment Details

* Package Name/Version: **libpq/16.8**
* Operating System+version: **macOS Sequoia 15.5**
* Compiler+version: **Clang 17**
* Conan version: **conan 2.17.0**
* Python version: **Python 3.13.5**

### Conan profile

[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=16
os=Macos

### Steps to reproduce

conan install --requires libpq/16.8 --build=missing

### Logs

_

**Comment by neobrain** [comment]
This reproduces on all libpq versions packaged in CCI, from 14.9 to 16.8.

**Comment by gav2xlin** [comment]
@neobrain You are not alone

[https://postgrespro.com/list/thread-id/2733758](https://postgrespro.com/list/thread-id/2733758)
"That is, the function exists now in macOS' libc, and so configure's
does-it-link test for **HAVE_STRCHRNUL** finds it, but <string.h>
will not let you use it unless you monkey around with
export **MACOSX_DEPLOYMENT_TARGET**=15.4
or similar."

Apple broke compatibilty

**Comment by aiyolo** [comment]
> [@neobrain](https://github.com/neobrain) You are not alone
> 
> https://postgrespro.com/list/thread-id/2733758 "That is, the function exists now in macOS' libc, and so configure's does-it-link test for **HAVE_STRCHRNUL** finds it, but <string.h> will not let you use it unless you monkey around with export **MACOSX_DEPLOYMENT_TARGET**=15.4 or similar."
> 
> Apple broke compatibilty

Setting `export MACOSX_DEPLOYMENT_TARGET=15.4` works for me.

**Comment by kambala-decapitator** [comment]
correct way to express `export MACOSX_DEPLOYMENT_TARGET=15.4` in Conan is this entry in profile:
```
[settings]
os.version=15.4
```
