### PR TITLE
[m4] Add compatibility for GCC15 and use version ranges for all recipes in CCI

### LINKED ISSUE #29184: [package] m4/1.4.19: build fails with gcc>=15.1
### Description

We bumped m4 to version 1.4.20 to solve [this issue](https://github.com/conan-io/conan-center-index/pull/27632).

Although other packages that use m4/1.4.19 still have this issue. One example is openal-soft, which has the dependency chain of:

```
libalsa/1.2.10 <- libtool/2.4.7 <-m4/1.4.19
```

Thus openal-soft will fail to compile because libasla fails to compile because libtool fails to compile because m4 fails to compile with gcc>=15.1

### Package and Environment Details

* Package Name/Version: **openalsoft/1.23.1**
* Operating System+version: **ndeavourOS Linux x86_64**
* Compiler+version: **gcc version 15.2.1 20250813**
* Docker image: N/A
* Conan version: **Conan version 2.19.1**
* Python version: **3.13.7**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=15
os=Linux

### Steps to reproduce

conan install . 

### Logs

<details><summary>Click to expand log</summary>

```
Put your log output here
```

</details>

### PR DESCRIPTION
**Pull request by uilianries**
### Summary
Changes to recipe:  **m4/1.4.19**

#### Motivation

fixes #29184

/cc @cuppajoeman

#### Details

When building M4 1.4.19 using GCC15, some errors can be found, like:

```
src/lib/gl_list.h:755:40: error: expected identifier or '(' before 'gl_list_node_t'
  755 | GL_LIST_INLINE _GL_ATTRIBUTE_NODISCARD gl_list_node_t
```

The full build log with several errors can be checked here: [m4-1.4.19-linux-amd64-gcc15-release.log](https://github.com/user-attachments/files/24324916/m4-1.4.19-linux-amd64-gcc15-release.log)

Disabling warnings is not enough, as this error is related to the gnulib copied in m4, which does not support C23 (the default C and C++ standard for GCC15: https://gcc.gnu.org/gcc-15/changes.html#c). As a workaround, we keep C17 for GCC15 and it works just fine:

[m4-1.4.19-linux-amd64-gcc15-cstd17-release.log](https://github.com/user-attachments/files/24325032/m4-1.4.19-linux-amd64-gcc15-cstd17-release.log)

The case was officially reported before: https://savannah.gnu.org/support/?111150, and it was fixed in 1.4.20 as a new release gnulib was incorporated into the project: https://lists.gnu.org/archive/html/m4-announce/2025-05/msg00000.html. Bringing a new gnulib version as a backport is not viable, but the Buildroot project had a good insight by keeping C17 for compatibility: https://lists.buildroot.org/pipermail/buildroot/2025-May/777741.html

This bug is affecting only 1.4.19, the versions 1.4.18 and 1.4.20 can be built using GCC15 without errors:

- [m4-1.4.18-linux-amd64-gcc15-release.log](https://github.com/user-attachments/files/24325076/m4-1.4.18-linux-amd64-gcc15-release.log)
- [m4-1.4.20-linux-amd64-gcc15-release.log](https://github.com/user-attachments/files/24325077/m4-1.4.20-linux-amd64-gcc15-release.log)

To avoid future conflicts and to keep aligned with the latest version available, this PR also updates all recipes in ConanCenterIndex that are consuming the package for m4 to use version ranges.

-----

A second error appeared during the CI when building using Apple Clang 17, related to incompatible function pointer types:

- https://github.com/conan-io/conan-center-index/pull/29220/checks?check_run_id=58858365285
- https://github.com/conan-io/conan-center-index/pull/29220/checks?check_run_id=58868002204

As a workaround, I just passed `-Wno-error=incompatible-pointer-types` to ignore it for now.

-----

A third error occurred on the Windows test package during the CI validation:

- https://github.com/conan-io/conan-center-index/pull/29220/checks?check_run_id=72850498293

The shebang for Perl is hardcoded in autoconf and other scripts, using the path from a previous Perl used in the CI, a location that no longer exists. 

I pushed the commit [ed37329](https://github.com/conan-io/conan-center-index/pull/29220/commits/ed373291c4590e258cae67c85af14cb3a00c5d62) which includes a new proper patch that covers all 2.72 files, so the shebang is no longer hardcoded. 

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] If this is a bug fix, please link related issue or provide bug details
- [x] Tested locally with at least one configuration using a recent version of Conan

---
Add a :+1: reaction to pull requests you find [important](https://github.com/conan-io/conan-center-index/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc) to help the team prioritize, thanks!

### CODE REVIEW

**Review by exief — APPROVED** [review]

**Review by exief — APPROVED** [review]

**Review by CJCombrink — APPROVED** [review]

**Comment by CJCombrink** [comment]
@uilianries Any updates on this?

**Comment by uilianries** [comment]
@CJCombrink Hello, you can use `m4/1.4.20` as usual by `replace_tool_requires`. Please, check my last comment: https://github.com/conan-io/conan-center-index/issues/29184#issuecomment-3687190012

**Comment by uilianries** [comment]
Hello all! This PR was moved to #30079 to keep simplicity, so we only touch m4 recipe.

Still, the CCI largely uses 1.4.19, which should be covered by that backport.

In case needing to use `m4/1.4.20`, you can use Conan [replace_tool_requires](https://docs.conan.io/2/reference/config_files/profiles.html#replace-tool-requires) to specify a different m4 version without changing the recipe. It will need to be added to the Conan profile:

```ini
# ~/.conan2/profiles/default
...

[replace_tool_requires]
m4/*: m4/1.4.20
```

This entry tells Conan to use `m4/1.4.20` for any m4 version consumed. 

In case of finding a new limitation regarding m4 and GCC-15, please refer in a new issue. Regards!
