### ISSUE TITLE
[package] openssl/1.1.1*: Lacks support for Conan 2.0

### ISSUE THREAD

**Issue by System-Arch** [conan-io/conan-center-index#13991]
### Description

OpenSLL 1.1.1* fails to build with Conan 2.0

### Package and Environment Details

Package Name/Version: openssl/1.1.1s
Operating System+version: Debian 10.3
Compiler+version: GCC 8
Conan version: conan 2.0.0.0beta4
Python version: Python 3.7.3

### Conan profile

Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux

### Steps to reproduce

conan-2.0 create . --version 1.1.1s

### Logs

<details><summary>Click to expand log</summary>

```
conan-2.0 create . --version 1.1.1s -pr:b tools.jinja -pr:h tools.jinja
Exporting the recipe
ERROR: Error loading conanfile at '/tmp/tmp.8Oz3wKaCCB/openssl/conanfile.py': Unable to load conanfile in /tmp/tmp.8Oz3wKaCCB/openssl/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmp.8Oz3wKaCCB/openssl/conanfile.py", line 6, in <module>
    from conans import AutoToolsBuildEnvironment, tools
ImportError: cannot import name 'AutoToolsBuildEnvironment' from 'conans' (/mathworks/devel/sandbox/marc/conan-2.0/conan-io/conans/__init__.py)
```

</details>

**Comment by System-Arch** [comment]
I have proposed fixes for these issues that I will submit as pull request.
