### ISSUE TITLE
[package] glog/0.6.0: Don't finds gflags with conan 2.0

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [conan-io/conan-center-index#16337]
### Description

Hi conan community,

Using an example (https://github.com/EstebanDugueperoux2/glog_test), it works with conan 1.59.0 but not with 2.0.0 release.
With 2.0.0 I get:

```
/home/conan/.conan2/p/glogb51c26a03204b/p/include/glog/logging.h:89:10: fatal error: gflags/gflags.h: No such file or directory
```

Regards.

### Package and Environment Details

* Package Name/Version: **glog/0.6.0**
* Compiler+version: **GCC 10**
* Docker image: **conanio/gcc10-ubuntu18.04**
* Conan version: **conan 2.0.0**

### Conan profile

[settings]
os=Linux
arch=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release

### Steps to reproduce

conan create . --profile:build .conan/profiles/gcc10 --profile:host .conan/profiles/gcc10 --build missing  -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True

### Logs

<details><summary>Click to expand log</summary>

```
test/0.0.1: Running CMake.build()
test/0.0.1: RUN: cmake --build "/home/conan/.conan2/p/t/test40f3ed19ff62f/b/build/Release" -- -j2
Scanning dependencies of target test
[ 50%] Building CXX object CMakeFiles/test.dir/src/test.cpp.o
In file included from /home/conan/.conan2/p/t/test40f3ed19ff62f/b/src/test.cpp:3:
/home/conan/.conan2/p/glogb51c26a03204b/p/include/glog/logging.h:89:10: fatal error: gflags/gflags.h: No such file or directory
   89 | #include <gflags/gflags.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/test.dir/build.make:62: recipe for target 'CMakeFiles/test.dir/src/test.cpp.o' failed
make[2]: *** [CMakeFiles/test.dir/src/test.cpp.o] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/test.dir/all' failed
make[1]: *** [CMakeFiles/test.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

test/0.0.1: ERROR: 
Package 'b8d23f4b22d977224e6aa923066bfc1cbbfc9c15' build failed
test/0.0.1: WARN: Build folder /home/conan/.conan2/p/t/test40f3ed19ff62f/b/build/Release
*********************************************************
Recipe 'test/0.0.1' cannot build its binary
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html
If it is your recipe, check it is updated to 2.0
*********************************************************

ERROR: test/0.0.1: Error in build() method, line 47
        cmake.build()
        ConanException: Error 2 while executing
```

</details>

**Comment by SpaceIm** [comment]
Will be fixed by https://github.com/conan-io/conan-center-index/pull/16257
