### PR TITLE
gettext: include stdlib.h on 0.21

### PR DESCRIPTION
**Pull request by toge**
Specify library name and version:  **gettext/0.21**

I met compilation error on gcc 14.1.1:
```
getted9230827dca7c/b/src/gettext-tools/src/locating-rule.c: In function ‘locating_rule_match’:
getted9230827dca7c/b/src/gettext-tools/src/locating-rule.c:150:7: error: implicit declaration of function ‘free’ [-Wimplicit-function-declaration]
  150 |       free (reduced);
      |       ^~~~
getted9230827dca7c/b/src/gettext-tools/src/locating-rule.c:50:1: note: include ‘<stdlib.h>’ or provide a declaration of ‘free’
   49 | #include "xalloc.h"
  +++ |+#include <stdlib.h>
   50 | 
getted9230827dca7
```

While gettext/0.22.5 works fine on gcc 14.1.1, gettext/0.21 is required by several important recipes (harfbuzz, pulseaudio, tre).

To minimize the impact, it would be better to create an adhoc patch  rather than upgrade gettext to 0.22.5.

Please point out if it would be better to increase the version of gettext rather than such an adhoc patch.

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by joeperri95 — APPROVED** [review]
Thank you for this. With this patch, I was able to build pulseaudio with gcc 14.

File: recipes/gettext/all/conandata.yml [hunk 1]
```diff
@@ -24,6 +24,9 @@ patches:
       patch_description: "apply the __atribute_noreturn__ to print_and_abort"
       patch_source: "https://github.com/coreutils/gnulib/commit/0cc39712803ade7b2d4b89c36b143dad72404063"
       patch_type: "conan"
+    - patch_file: "patches/0.21-include-stdlib_h.patch"
+      patch_description: "include stdlib.h for newer gcc"
+      patch_type: "portability"
```
Comment (RubenRBS) [inline recipes/gettext/all/conandata.yml:29]: If this is solved in 0.22, it would fall under the backport category. We're more likely to prefer this option if you can find the commit that fixed this for that verison and link it in the `patch_source` field. Wdyt @toge?

**Review by RubenRBS — COMMENTED** [review]
Thanks! Small comment after consulting with @uilianries

**Review by jcar87 — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]
