### ISSUE TITLE
[package] Cpython/3.10.0: Unable to build due preprocessor errors

### ISSUE THREAD

**Issue by MaxKarel** [conan-io/conan-center-index#23260]
### Description

After the recent merge of CPython (thx @Ahajha) I was able to use it in our custom recipe without a problem. But sadly for windows I was not able to make it work. The build fails with this error:

```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(253): error RC2188: C:\.conan\ef7f71\1\src\PCbui
ld\obj\310amd64_Debug\venvlauncher\RCa04680(61) : fatal error RC1116: RC terminating after preprocessor errors [C:\.con
an\ef7f71\1\src\PCbuild\venvlauncher.vcxproj]
```

I have seen that you are also working on other open PR and task lists regarding python. So maybe you already know about this issue.

### Package and Environment Details

* Package Name/Version: **cpython/3.10.0**
* Operating System+version: **Windows 10**
* Compiler+version: **Visual Studio 15**
* Conan version: **conan 1.59.0**
* Python version: **Python 3.11.4**

### Conan profile

[settings]
arch=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=15
os=Windows
[options]
shared=True
[build_requires]
[env]

### Steps to reproduce

conan install cpython/3.10.0@ -oshared=True --build=missing

### Logs

<details><summary>Click to expand log</summary>

```
WARN: tcl/8.6.10: requirement zlib/[>=1.2.11 <2] overridden by tk/8.6.10 to zlib/1.2.13
cpython/3.10.0: WARN: Package binary is corrupted, removing: 89849ad3b8e70706b1667227c91e7bee35ed4a69
Version ranges solved
    Version range '>=1.2.11 <2' required by 'cpython/3.10.0' resolved to 'zlib/1.2.13' in local cache
    Version range '>=1.1 <4' required by 'cpython/3.10.0' resolved to 'openssl/3.0.5' in local cache
    Version range '>=1.2.11 <2' required by 'tcl/8.6.10' valid for downstream requirement 'zlib/1.2.13'

Installing package: cpython/3.10.0
Requirements
    bzip2/1.0.8 from 'skeletex-repo' - Cache
    cpython/3.10.0 from 'conancenter' - Cache
    expat/2.6.0 from 'conancenter' - Cache
    libffi/3.4.4 from 'conancenter' - Cache
    mpdecimal/2.5.1 from 'conancenter' - Cache
    openssl/3.0.5 from 'skeletex-repo' - Cache
    sqlite3/3.45.0 from 'conancenter' - Cache
    tcl/8.6.10 from 'conancenter' - Cache
    tk/8.6.10 from 'conancenter' - Cache
    xz_utils/5.6.1 from 'conancenter' - Cache
    zlib/1.2.13 from 'skeletex-repo' - Cache
Packages
    bzip2/1.0.8:5c382ca84120276840c8074ab1851697636fb8ae - Cache
    cpython/3.10.0:89849ad3b8e70706b1667227c91e7bee35ed4a69 - Build
    expat/2.6.0:f18ca2b6146562db732c218783c1eb027216cdcd - Cache
    libffi/3.4.4:8cf01e2f50fcd6b63525e70584df0326550364e1 - Cache
    mpdecimal/2.5.1:3f9fc980b341253ac84c48dd509631305c31ebdd - Cache
    openssl/3.0.5:f182a487f54c12b51d9bb57c798aacb2b6f82d1b - Cache
    sqlite3/3.45.0:8e25da653fbb0e3f07cb3452f2043ed8c19025be - Cache
    tcl/8.6.10:009a50ddeb47afbc9361cbc63650560c127e1234 - Cache
    tk/8.6.10:804ca491717e7eb038bd819a0048ceebe33bc500 - Cache
    xz_utils/5.6.1:8cf01e2f50fcd6b63525e70584df0326550364e1 - Cache
    zlib/1.2.13:8cf01e2f50fcd6b63525e70584df0326550364e1 - Cache

Installing (downloading, building) binaries...
bzip2/1.0.8: Already installed!
expat/2.6.0: Already installed!
libffi/3.4.4: Already installed!
mpdecimal/2.5.1: Already installed!
sqlite3/3.45.0: Already installed!
xz_utils/5.6.1: Already installed!
zlib/1.2.13: Already installed!
openssl/3.0.5: Already installed!
tcl/8.6.10: Already installed!
tk/8.6.10: Already installed!
tk/8.6.10: Setting TK_LIBRARY environment variable: C:/GitLab-Runner/builds/.conan/data/tk/8.6.10/_/_/package/804ca491717e7eb038bd819a0048ceebe33bc500/lib/tk8.6
tk/8.6.10: Setting TK_ROOT environment variable: C:/GitLab-Runner/builds/.conan/data/tk/8.6.10/_/_/package/804ca491717e7eb038bd819a0048ceebe33bc500
cpython/3.10.0: WARN: Build folder is dirty, removing it: C:\.conan\ef7f71\1
cpython/3.10.0: Copying sources to build folder
cpython/3.10.0: Building your package in C:\.conan\ef7f71\1
cpython/3.10.0: Generator txt created conanbuildinfo.txt
cpython/3.10.0: Calling generate()
cpython/3.10.0: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
cpython/3.10.0: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
cpython/3.10.0: MSBuildToolchain created conantoolchain_debug_x64.props
cpython/3.10.0: MSBuildToolchain writing conantoolchain.props
cpython/3.10.0: Aggregating env generators
cpython/3.10.0: Calling build()
cpython/3.10.0: Apply patch (conan): Version specific patches to MSVC projects to allow injection of dependencies
cpython/3.10.0: Apply patch (bugfix): Fix ARM/ARM64 mismatch in project file
cpython/3.10.0: Apply patch (portability): Remove duplicate libffi symbols and support shared libffi
cpython/3.10.0: Apply patch (bugfix): Pass C and CPP flags from configure script to setup.py
cpython/3.10.0: Apply patch (conan): Unconditionally enable tcl/tk on Mac
cpython/3.10.0: Apply patch (conan): Allow package to be relocatable
cpython/3.10.0: Patching runtime
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\liblzma.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\openssl.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\pylauncher.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\pyshellext.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\python.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\python3dll.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\pythonw.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\pythonw_uwp.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\python_uwp.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\pywlauncher.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\select.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\sqlite3.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\tcl.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\tix.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\tk.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\unicodedata.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\venvlauncher.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\venvwlauncher.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\winsound.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\xxlimited.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\xxlimited_35.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\_asyncio.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\_ctypes_test.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\_freeze_importlib.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\_msi.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\_multiprocessing.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\_overlapped.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\_queue.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\_socket.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\_testbuffer.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\_testcapi.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\_testconsole.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\_testembed.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\_testimportmultiple.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\_testinternalcapi.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\_testmultiphase.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\_uuid.vcxproj' file.
cpython/3.10.0: WARN: replace_in_file didn't find pattern 'CONAN_REPLACE_HERE' in 'C:\.conan\ef7f71\1\src\PCbuild\_zoneinfo.vcxproj' file.
cpython/3.10.0: Building 30 Visual Studio projects: ['venvlauncher', 'python', '_msi', '_multiprocessing', 'select', '_socket', 'venvwlauncher', '_ssl', '_zoneinfo', '_bz2', '_ctypes', '_lzma', '_tkinter', 'pythoncore', '_hashlib', 'pyexpat', 'winsound', 'pylauncher', 'python3dll', 'pyshellext', 'pythonw', '_sqlite3', '_decimal', 'pywlauncher', '_overlapped', '_uuid', '_elementtree', '_asyncio', 'unicodedata', '_queue']
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.59
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 25/03/2024 15:30:55.
Project "C:\.conan\ef7f71\1\src\PCbuild\pcbuild.sln" on node 1 (venvlauncher;python;_msi;_multiprocessing;select;_socke
t;venvwlauncher;_ssl;_zoneinfo;_bz2;_ctypes;_lzma;_tkinter;pythoncore;_hashlib;pyexpat;winsound;pylauncher;python3dll;p
yshellext;pythonw;_sqlite3;_decimal;pywlauncher;_overlapped;_uuid;_elementtree;_asyncio;unicodedata;_queue target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|x64".
ValidateProjects:
  The project "xxlimited" is not selected for building in solution configuration "Debug|x64".
  The project "_freeze_importlib" is not selected for building in solution configuration "Debug|x64".
Project "C:\.conan\ef7f71\1\src\PCbuild\pcbuild.sln" (1) is building "C:\.conan\ef7f71\1\src\PCbuild\venvlauncher.vcxpr
oj" (2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "C:\.conan\ef7f71\1\src\PCbuild\obj\310amd64_Debug\venvlauncher\".
  Creating directory "C:\.conan\ef7f71\1\src\PCbuild\amd64\".
  Creating directory "C:\.conan\ef7f71\1\src\PCbuild\obj\310amd64_Debug\venvlauncher\venvlauncher.tlog\".
InitializeBuildStatus:
  Creating "C:\.conan\ef7f71\1\src\PCbuild\obj\310amd64_Debug\venvlauncher\venvlauncher.tlog\unsuccessfulbuild" because
   "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\CL.exe /c /IC
  :\.conan\ef7f71\1\src\Include /IC:\.conan\ef7f71\1\src\Include\internal /IC:\.conan\ef7f71\1\src\PC /IC:\.conan\ef7f7
  1\1\src\PCbuild\obj\310amd64_Debug\venvlauncher\ /Zi /nologo /W3 /WX- /diagnostics:classic /Od /Ob1 /Oi /D _CONSOLE /
  D VENV_REDIRECT /D WIN32 /D "PY3_DLLNAME=L\"python3_d\"" /D _WIN64 /D _M_X64 /D _DEBUG /D _MBCS /GF /Gm- /MT /GS /Gy
  /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"C:\.conan\ef7f71\1\src\PCbuild\obj\310amd64_Debug\venvlauncher\\"
   /Fd"C:\.conan\ef7f71\1\src\PCbuild\obj\310amd64_Debug\venvlauncher\vc141.pdb" /Gd /TC /FC /errorReport:queue /utf-8
  ..\PC\launcher.c
  launcher.c
ResourceCompile:
  C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x86\rc.exe /D PY_ICON /D "ORIGINAL_FILENAME=\\\"venvlauncher_
  d.exe\\\"" /D FIELD3=150 /D _DEBUG /l"0x0409" /IC:\.conan\ef7f71\1\src\PC /IC:\.conan\ef7f71\1\src\Include /IC:\.cona
  n\ef7f71\1\src\PCbuild\obj\310amd64_Debug\venvlauncher\ /nologo /fo"C:\.conan\ef7f71\1\src\PCbuild\obj\310amd64_Debug
  \venvlauncher\pylauncher.res" ..\PC\pylauncher.rc
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(253): error RC2188: C:\.conan\ef7f71\1\src\PCbui
ld\obj\310amd64_Debug\venvlauncher\RCa04680(61) : fatal error RC1116: RC terminating after preprocessor errors [C:\.con
an\ef7f71\1\src\PCbuild\venvlauncher.vcxproj]

Done Building Project "C:\.conan\ef7f71\1\src\PCbuild\venvlauncher.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\.conan\ef7f71\1\src\PCbuild\pcbuild.sln" (venvlauncher;python;_msi;_multiprocessing;select;_s
ocket;venvwlauncher;_ssl;_zoneinfo;_bz2;_ctypes;_lzma;_tkinter;pythoncore;_hashlib;pyexpat;winsound;pylauncher;python3d
ll;pyshellext;pythonw;_sqlite3;_decimal;pywlauncher;_overlapped;_uuid;_elementtree;_asyncio;unicodedata;_queue target(s
)) -- FAILED.


"C:\.conan\ef7f71\1\src\PCbuild\pcbuild.sln" (venvlauncher;python;_msi;_multiprocessing;select;_socket;venvwlauncher;_s
sl;_zoneinfo;_bz2;_ctypes;_lzma;_tkinter;pythoncore;_hashlib;pyexpat;winsound;pylauncher;python3dll;pyshellext;pythonw;
_sqlite3;_decimal;pywlauncher;_overlapped;_uuid;_elementtree;_asyncio;unicodedata;_queue target) (1) ->
"C:\.conan\ef7f71\1\src\PCbuild\venvlauncher.vcxproj" (default target) (2) ->
(ResourceCompile target) ->
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(253): error RC2188: C:\.conan\ef7f71\1\src\PCb
uild\obj\310amd64_Debug\venvlauncher\RCa04680(61) : fatal error RC1116: RC terminating after preprocessor errors [C:\.c
onan\ef7f71\1\src\PCbuild\venvlauncher.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.94
cpython/3.10.0:
cpython/3.10.0: ERROR: Package '89849ad3b8e70706b1667227c91e7bee35ed4a69' build failed
cpython/3.10.0: WARN: Build folder C:\.conan\ef7f71\1\build-debug
ERROR: cpython/3.10.0: Error in build() method, line 404
        self._msvc_build()
while calling '_msvc_build', line 399
        self.run(f"{cmd} /p:PlatformToolset={msvs_toolset(self)}")
        ConanException: Error 1 while executing msbuild "C:\.conan\ef7f71\1\src\PCbuild\pcbuild.sln" /p:Configuration=Debug /p:Platform=x64 /target:venvlauncher;python;_msi;_multiprocessing;select;_socket;venvwlauncher;_ssl;_zoneinfo;_bz2;_ctypes;_lzma;_tkinter;pythoncore;_hashlib;pyexpat;winsound;pylauncher;python3dll;pyshellext;pythonw;_sqlite3;_decimal;pywlauncher;_overlapped;_uuid;_elementtree;_asyncio;unicodedata;_queue /p:PlatformToolset=v141```

</details>

**Comment by Ahajha** [comment]
My guess is it has something to do with Visual Studio 15 being used. I haven't run into this issue myself, but I'll look into what might be causing this.

**Comment by MaxKarel** [comment]
Yes its probably it. I have updated my profile to use `compiler.version=16` and there were no issues with compilation with Visual Studio 2019

**Comment by MaxKarel** [comment]
Possibly unrelated but i was not able to specify `-oshared=True`
```
ERROR: C:\Users\Max Karel\test\conan-center-index\recipes\cpython\all\test_package\conanfile.py: option 'shared' doesn't exist
Possible options are []
```
But after changing value to true I get error in one of the tests:
```
cpython/3.10.14@ahajha/testing (test package): Running test()
Python 3.10.14
hello world
cpython/3.10.14@ahajha/testing (test package): 3.10.14

  File "C:\Users\Max", line 1
    [05F0:4A28][2022-12-12T13:51:32]i001: Burn v3.10.4.4718, Windows v10.0 (Build 19044: Service Pack 0), path: C:\WINDOWS\Temp\{F838A050-2E8D-4FFF-B50A-A72E7D936B15}\.cr\VC_redist.x64.exe
     ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
cpython/3.10.14@ahajha/testing (test package): Module failed as expected
  File "C:\Users\Max", line 1
    [05F0:4A28][2022-12-12T13:51:32]i001: Burn v3.10.4.4718, Windows v10.0 (Build 19044: Service Pack 0), path: C:\WINDOWS\Temp\{F838A050-2E8D-4FFF-B50A-A72E7D936B15}\.cr\VC_redist.x64.exe
     ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
cpython/3.10.14@ahajha/testing (test package): WARN: Module 'bz2' does not work, but should have worked
ERROR: cpython/3.10.14@ahajha/testing (test package): Error in test() method, line 161
        self._test_module("bz2", self._cpython_option("with_bz2"))
while calling '_test_module', line 133
        self.run(f"{self._python} {self.source_folder}/test_package.py -b {self.build_folder} -t {module}", env="conanrun")
        ConanException: Error 1 while executing C:\.conan\a5436f\1\bin\python_d.exe C:\Users\Max Karel\test\conan-center-index\recipes\cpython\all\test_package\./test_package.py -b C:\Users\Max Karel\test\conan-center-index\recipes\cpython\all\test_package\build -t bz2
```


Also, you have removed the check for shared lib and version higher than 3.10.0 without it I get:
```
ERROR: There are invalid packages (packages that cannot exist for this configuration):
cpython/3.10.14@ajhaha/testing: Invalid ID: Static msvc build disabled (>=3.10) due to "AttributeError: module 'sys' has no attribute 'winver'"
```

**Comment by Ahajha** [comment]
Maybe try `-o cpython/*:shared=True` instead of `-oshared=True`, that's the way it has to be specified in Conan 2.0 (and works in Conan 1 as well).

Static builds don't work in 3.10.0+, they're only supported on a best-effort basis but haven't properly worked in a while: https://github.com/python/cpython/issues/110234

That error is curious, seems like it's outputting something completely unrelated, and then trying to parse it as python code? Do you have spaces in your filepath?

**Comment by Ahajha** [comment]
Just pushed the spaces in filepath fix, can you try again?

**Comment by Ahajha** [comment]
The new versions are merged, FYI.
