### ISSUE TITLE
[package] libudev/system: Fails build for conan 2.0

### ISSUE THREAD

**Issue by tannerbitz** [conan-io/conan-center-index#16238]
### Description

libudev/system fails to download or build with conan 2.0 installed.  it needs an update to use conan 2.0 code for conan tools as it currently is dependent on conan 1.x code.   

### Package and Environment Details

* Package Name/Version: **libudev/system**
* Operating System+version: **Linux Ubuntu 20.04**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux

### Steps to reproduce

conan download -r conancenter libudev/system@

### Logs

ERROR: Error loading conanfile at '/home/tbitz/.conan2/p/libudadcb0d08572c6/e/conanfile.py': Unable to load conanfile in /home/tbitz/.conan2/p/libudadcb0d08572c6/e/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/tbitz/.conan2/p/libudadcb0d08572c6/e/conanfile.py", line 4, in <module>
    from conans import tools
ImportError: cannot import name 'tools' from 'conans' (/home/tbitz/.local/lib/python3.8/site-packages/conans/__init__.py)

**Comment by tannerbitz** [comment]
I would like to help update this package's recipe

**Comment by jcar87** [comment]
Hi @tannerbitz, thanks so much for trying Conan 2.0 on release day and for offering your help giving the finishing touches to this recipe :) 

From what I can see, this recipe is fairly similar to this one: 
https://github.com/conan-io/conan-center-index/blob/master/recipes/egl/system/conanfile.py

and the changes needed to make it compatible with Conan 2.0 are similar to the ones that went in this PR:
https://github.com/conan-io/conan-center-index/pull/16172

in terms of using the newer PkgConfig integration and relying on its built-in implementation for `fill_cpp_info` 

Let me know if you need more info and I'll be happy to assist, cheers!

**Comment by tannerbitz** [comment]
That's the exact recipe I found while making the ports!  Will get the PR up soon
