### ISSUE TITLE
qt/5.15.2: fails to build on macOS 12.0.1 Monterrey

### ISSUE THREAD

**Issue by yuriy-mochurad** [conan-io/conan-center-index#7942]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: qt/5.15.2
  * Operating System+version: macOS 12.0.1
  * Compiler+version: clang 13
  * Conan version: 1.42.0
  * Python version: 3.9.7

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Macos
os_build=Macos
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13.0
build_type=Release
arch=x86_64
arch_build=x86_64
[options]
[conf]
[build_requires]
[env]
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
compiling ~/.conan/data/qt/5.15.2/_/_/source/qt5/qtbase/src/plugins/platforms/cocoa/qcocoasessionmanager.cpp
In file included from ~/.conan/data/qt/5.15.2/_/_/source/qt5/qtbase/src/plugins/platforms/cocoa/qiosurfacegraphicsbuffer.mm:40:
~/.conan/data/qt/5.15.2/_/_/source/qt5/qtbase/src/plugins/platforms/cocoa/qiosurfacegraphicsbuffer.h:54:32: error: unknown type name 'CGColorSpaceRef'; did you mean 'QColorSpace'?
    void setColorSpace(QCFType<CGColorSpaceRef> colorSpace);
                               ^~~~~~~~~~~~~~~
                               QColorSpace
~/conan/data/qt/5.15.2/_/_/source/qt5/qtbase/include/QtCore/../../src/corelib/kernel/qmetatype.h:2090:1: note: 'QColorSpace' declared here
QT_FOR_EACH_STATIC_GUI_CLASS(QT_FORWARD_DECLARE_STATIC_TYPES_ITER)
^
~/.conan/data/qt/5.15.2/_/_/source/qt5/qtbase/include/QtCore/../../src/corelib/kernel/qmetatype.h:178:24: note: expanded from macro 'QT_FOR_EACH_STATIC_GUI_CLASS'
    F(QColorSpace, 87, QColorSpace) \
                       ^
~/.conan/data/qt/5.15.2/_/_/source/qt5/qtbase/src/plugins/platforms/cocoa/qiosurfacegraphicsbuffer.mm:90:32: error: out-of-line definition of 'setColorSpace' does not match any declaration in 'QIOSurfaceGraphicsBuffer'
void QIOSurfaceGraphicsBuffer::setColorSpace(QCFType<CGColorSpaceRef> colorSpace)
                               ^~~~~~~~~~~~~
~/.conan/data/qt/5.15.2/_/_/source/qt5/qtbase/src/plugins/platforms/cocoa/qiosurfacegraphicsbuffer.h:54:24: note: type of 1st parameter of member declaration does not match definition ('QCFType<QColorSpace>' vs 'QCFType<CGColorSpaceRef>')
    void setColorSpace(QCFType<CGColorSpaceRef> colorSpace);
                       ^
2 errors generated.

```

</details>

**Comment by ericLemanissier** [comment]
I think this patch is needed for qt5 too: https://github.com/conan-io/conan-center-index/blob/master/recipes/qt/6.x.x/patches/dece6f5.patch
Can you please make a pull request to add it?
