### PR TITLE
googleapis: modernize more & bump protobuf

### PR DESCRIPTION
**Pull request by SpaceIm**
- trick to avoid having protobuf both in requirements & build requirements (if native build for 1 & 2 profiles)
- use rm_safe
- use self.dependencies
- use tool_requires
- reorder methods by order of execution to give a better understanding of global recipe logic

---

- [ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by jcar87** [comment]
From my own local testing, I'm pretty sure that `googleapis` simply does _not_ build with Protobuf 3.21.9 on macOS, due to a clash between a macro defined in the system's `syslimits.h` and code generated by `protoc`. 

It's unclear why it went from working (3.21.4) to not working (3.21.9), but it could be simply be caused as a side effect of the order of implicitly included headers changing.


```
/Users/jenkins/w/prod/BuildSingleReference@7/.conan/data/googleapis/cci.20220531/_/_/build/d52f4199324621c40024ef7b88e1b3bafd1d4af3/build/Release/google/storagetransfer/v1/transfer_types.pb.h:3520:24: error: expected member name or ';' after declaration specifiers
  static constexpr GID GID_MAX =
  ~~~~~~~~~~~~~~~~~~~~ ^
/Applications/conan/xcode/11.0/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/sys/syslimits.h:78:28: note: expanded from macro 'GID_MAX'
#define GID_MAX            2147483647U  /* max value for a gid_t (2^31-2) */
                           ^
1 error generated.
```

this _may_ be fixed in newer versions of protobuf:
https://github.com/protocolbuffers/protobuf/blob/v22.0/src/google/protobuf/port_def.inc#L971-L972

**Comment by prince-chrismc** [comment]
There's merge conflicts and the downstream dep was fixed should be good to move forward

**Comment by SpaceIm** [comment]
```
/opt/conan/binutils/bin/ld: CMakeFiles/test_package.dir/test_package.cpp.o: undefined reference to symbol '_ZNK6google8protobuf7Message11DebugStringB5cxx11Ev'
/opt/conan/binutils/bin/ld: /home/conan/w/prod-v2/BuildSingleReference/p/protoe1ed88265f4f3/p/lib/libprotobuf.so.32: error adding symbols: DSO missing from command line
```

well, transitive_libs is missing

File: recipes/googleapis/all/conanfile.py [hunk 1]
```diff
@@ -25,39 +26,42 @@ class GoogleAPIS(ConanFile):
...
     def configure(self):
         if self.options.shared:
             self.options.rm_safe("fPIC")
             self.options["protobuf"].shared = True
 
+    def layout(self):
+        cmake_layout(self, src_folder="src")
+
+    def requirements(self):
+        self.requires(f"protobuf/{self._protobuf_version}", transitive_headers=True, transitive_libs=True, run=can_run(self))
```
Comment (prince-chrismc) [inline recipes/googleapis/all/conanfile.py:61]: Please add  comment for Transitive libs 🙏

File: recipes/googleapis/all/conanfile.py [hunk 2]
```diff
@@ -67,28 +71,35 @@ def validate(self):
         if self.options.shared and not self.dependencies["protobuf"].options.shared:
             raise ConanInvalidConfiguration("If built as shared, protobuf must be shared as well. Please, use `protobuf:shared=True`")
 
-    @property
-    def _cmake_new_enough(self):
+    def _cmake_new_enough(self, required_version):
```
Comment (prince-chrismc) [inline recipes/googleapis/all/conanfile.py:74]: This is can be removed with the new portable binaries

**Comment by prince-chrismc** [comment]
Super minor nits

File: recipes/googleapis/all/conanfile.py (hunk 1 above)
Comment (prince-chrismc) [reply recipes/googleapis/all/conanfile.py:61]:
```suggestion
        # https://github.com/conan-io/conan-center-index/pull/15601#issuecomment-1493086506
        self.requires(f"protobuf/{self._protobuf_version}", transitive_headers=True, transitive_libs=True, run=can_run(self))
```

Comment (SpaceIm) [reply recipes/googleapis/all/conanfile.py:61]: I'll do since conan team seams to be obsessed by this, not sure it's worth the massive time it takes to rebuild...

**Review by prince-chrismc — APPROVED** [review]

**Comment by prince-chrismc** [comment]
#16034 has the same changes so we will have merge conflicts :(

**Review by SSE4 — APPROVED** [review]
