### PR TITLE
OpenSSL 1.x.x Conan 2.0 compatibility

### LINKED ISSUE #13991: [package] openssl/1.1.1*: Lacks support for Conan 2.0
### Description

OpenSLL 1.1.1* fails to build with Conan 2.0

### Package and Environment Details

Package Name/Version: openssl/1.1.1s
Operating System+version: Debian 10.3
Compiler+version: GCC 8
Conan version: conan 2.0.0.0beta4
Python version: Python 3.7.3

### Conan profile

Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux

### Steps to reproduce

conan-2.0 create . --version 1.1.1s

### Logs

<details><summary>Click to expand log</summary>

```
conan-2.0 create . --version 1.1.1s -pr:b tools.jinja -pr:h tools.jinja
Exporting the recipe
ERROR: Error loading conanfile at '/tmp/tmp.8Oz3wKaCCB/openssl/conanfile.py': Unable to load conanfile in /tmp/tmp.8Oz3wKaCCB/openssl/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmp.8Oz3wKaCCB/openssl/conanfile.py", line 6, in <module>
    from conans import AutoToolsBuildEnvironment, tools
ImportError: cannot import name 'AutoToolsBuildEnvironment' from 'conans' (/mathworks/devel/sandbox/marc/conan-2.0/conan-io/conans/__init__.py)
```

</details>

### PR DESCRIPTION
**Pull request by System-Arch**
Specify library name and version:  **openssl/1.x.x**

Updated conanfile.py and test_package/conanfile.py to work with Conan 2.0.0-beta4 (Resolves #13991)

Changes involve leveraging Conan 2.0 generators and other syntactic changes

Tested on Linux, Windows, and Mac for 1.0.2u, 1.1.0l, and 1.1.1s
---

- [X] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [X] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by System-Arch** [comment]
Hi @prince-chrismc,

I believe the error quoted below and shown in conan-center-bot comments above is faulty as this recipe has been tested extensively with Conan 2.0-beta4 including on a Mac. I suspect the bot is using an older Conan 2 beta that lacks support for XCRun in conan.tools.apple.

> 🔸 Informative: This recipe is not ready for Conan v2
> We have started the [migration process to Conan v2](https://github.com/conan-io/conan-center-index/blob/master/docs/v2_roadmap.md) and exporting recipes successfully will be required in the future.
> This is just an informative note to gain awareness about the process, no need to take any action. The plan is to enforce smaller steps that are easier to fix and, eventually, this conan export step will work.
> See the [recipe migration guide](https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html#migrating-the-recipes) to know more about the changes required.
> 
> ERROR: Error loading conanfile at '/home/conan/w/prod_cci_PR-14066/recipes/openssl/1.x.x/conanfile.py': Unable to load conanfile in /home/conan/w/prod_cci_PR-14066/recipes/openssl/1.x.x/conanfile.py
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/conan/w/prod_cci_PR-14066/recipes/openssl/1.x.x/conanfile.py", line 7, in <module>
>     from conan.tools.apple import is_apple_os, XCRun
> ImportError: cannot import name 'XCRun' from 'conan.tools.apple' (/opt/pyenv/versions/3.7.13/lib/python3.7/site-packages/conan/tools/apple/__init__.py)
>

**Comment by prince-chrismc** [comment]
The team is working on deploying new images for 2.0 and 1.54 🤞 shouldn't be long this time

**Comment by System-Arch** [comment]
Hi @prince-chrismc,
I know the team is busy, but given that OpenSSL is one of the recipes listed in #12888, was wondering if there was any ETA on getting this PR reviewed. Or is there something I need to do that I missed? Thanks

**Comment by paulharris** [comment]
Does not build for me in an msys2 shell (building for vs17)
```
        IF EXIST apps\openssl.exe.manifest DEL /F /Q apps\openssl.exe.manifest
        link /nologo /debug /subsystem:console /opt:ref  /nologo /debug /out:apps\openssl.exe @C:\Users\paul\AppData\Local\Temp\nm8B3E.tmp
/usr/bin/link: extra operand ‘/subsystem:console’
Try '/usr/bin/link --help' for more information.
NMAKE : fatal error U1077: 'K:\git-sdk-64\usr\bin\link.EXE' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
openssl/1.1.1s@ccitest/check-14066:
openssl/1.1.1s@ccitest/check-14066: ERROR: Package 'f3b751d33d96e6e6e078d72425e33f334e0c01d9' build failed
openssl/1.1.1s@ccitest/check-14066: WARN: Build folder K:\env\conandata\openssl\1.1.1s\ccitest\check-14066\build\f3b751d33d96e6e6e078d72425e33f334e0c01d9
ERROR: openssl/1.1.1s@ccitest/check-14066: Error in build() method, line 767
        self._make()
while calling '_make', line 707
        self._run_make()
while calling '_run_make', line 662
        self.run(" ".join(command), win_bash=self._win_bash)
        ConanException: Error 2 while executing nmake
```

**Comment by paulharris** [comment]
I believe it does build in a DOS shell, same target compiler, same conan, same devenv.

**Comment by System-Arch** [comment]
> Does not build for me in an msys2 shell (building for vs17)
> 
> ```
>         IF EXIST apps\openssl.exe.manifest DEL /F /Q apps\openssl.exe.manifest
>         link /nologo /debug /subsystem:console /opt:ref  /nologo /debug /out:apps\openssl.exe @C:\Users\paul\AppData\Local\Temp\nm8B3E.tmp
> /usr/bin/link: extra operand ‘/subsystem:console’

Hi @paulharris,

Thanks for testing these changes. This appears to be a namespace collision  between the Visual Studio linker and the msys2 linker. I have tightened up the conditions under which msys2 is added as a build_requires. It would be great if you could try the latest version in your environment. Thanks

**Comment by paulharris** [comment]
> > Does not build for me in an msys2 shell (building for vs17)
> > ```
> >         IF EXIST apps\openssl.exe.manifest DEL /F /Q apps\openssl.exe.manifest
> >         link /nologo /debug /subsystem:console /opt:ref  /nologo /debug /out:apps\openssl.exe @C:\Users\paul\AppData\Local\Temp\nm8B3E.tmp
> > /usr/bin/link: extra operand ‘/subsystem:console’
> > ```
> 
> Hi @paulharris,
> 
> Thanks for testing these changes. This appears to be a namespace collision between the Visual Studio linker and the msys2 linker. I have tightened up the conditions under which msys2 is added as a build_requires. It would be great if you could try the latest version in your environment. Thanks

Just tested, it builds nicely on msys - well done!   I built 1.1.1s and will try 1.0.2u and 1.1.0l.   And on DOS.
Will message again if there are problems.

**Comment by System-Arch** [comment]
Hi @czoido,
If this change looks okay, can you review it? Thanks

File: recipes/openssl/1.x.x/conanfile.py [hunk 1]
```diff
@@ -169,15 +169,9 @@ def _settings_build(self):
...
-    @property
-    def _win_bash(self):
-        return self._settings_build.os == "Windows" and \
-               not self._use_nmake and \
-               (self._is_mingw or cross_building(self, skip_x64_x86=True))
-
     def export_sources(self):
         for patch in self.conan_data.get("patches", {}).get(self.version, []):
-            self.copy(patch["patch_file"])
+            copy(self, patch["patch_file"], self.recipe_folder, self.export_sources_folder )
```
Comment (czoido) [inline recipes/openssl/1.x.x/conanfile.py:174]: Maybe we could simplify a bit here using:

```
    def export_sources(self):
        export_conandata_patches(self)
```

File: recipes/openssl/1.x.x/conanfile.py [hunk 2]
```diff
@@ -911,8 +914,8 @@ def package_info(self):
         # TODO: to remove in conan v2 once cmake_find_package* generators removed
         self.cpp_info.names["cmake_find_package"] = "OpenSSL"
         self.cpp_info.names["cmake_find_package_multi"] = "OpenSSL"
-        self.cpp_info.components["ssl"].build_modules["cmake_find_package"] = [self._module_file_rel_path]
-        self.cpp_info.components["crypto"].build_modules["cmake_find_package"] = [self._module_file_rel_path]
+        #self.cpp_info.components["ssl"].build_modules["cmake_find_package"] = [self._module_file_rel_path]
+        #self.cpp_info.components["crypto"].build_modules["cmake_find_package"] = [self._module_file_rel_path]
```
Comment (czoido) [inline recipes/openssl/1.x.x/conanfile.py:918]: Why is it needed to comment this?

File: recipes/openssl/1.x.x/conanfile.py (hunk 1 above)
Comment (System-Arch) [reply recipes/openssl/1.x.x/conanfile.py:174]: Hi @czoido,
Yes, nice simplification

File: recipes/openssl/1.x.x/conanfile.py [hunk 3]
```diff
@@ -223,35 +216,61 @@ def config_options(self):
...
-
-    def layout(self):
-        pass
+            self.options.rm_safe("fPIC")
+        self.settings.rm_safe("compiler.libcxx")
+        self.settings.rm_safe("compiler.cppstd")
+        self.conf.define("tools.gnu:make_program", self._make_program)
 
     def requirements(self):
-        if self._full_version < "1.1.0" and self.options.get_safe("no_zlib") == False:
```
Comment (prince-chrismc) [inline recipes/openssl/1.x.x/conanfile.py:234]: I wonder what assumpt the old code was working with by remove this option https://github.com/openssl/openssl/blob/OpenSSL_1_1_1s/Configure#L475

Seems like it could have been enabled (so I think this option means something bizarre)

For me to test this use case locally

File: recipes/openssl/1.x.x/conanfile.py [hunk 4]
```diff
@@ -223,35 +216,61 @@ def config_options(self):
...
+        if self._full_version < "1.1.0" and not self.options.get_safe("no_zlib"):
             self.requires("zlib/1.2.12")
 
     def validate(self):
-        if self.settings.os == "Emscripten":
+        if self.info.settings.os == "Emscripten":
```
Comment (prince-chrismc) [inline recipes/openssl/1.x.x/conanfile.py:229]: This advice has changed in recent weeks

```suggestion
        if self.settings.os == "Emscripten":
```

File: recipes/openssl/1.x.x/conanfile.py [hunk 5]
```diff
@@ -223,35 +216,61 @@ def config_options(self):
...
     def build_requirements(self):
         if self._settings_build.os == "Windows":
-            if not self._win_bash:
-                self.build_requires("strawberryperl/5.30.0.1")
-            if not self.options.no_asm and not tools.which("nasm"):
-                self.build_requires("nasm/2.15.05")
-        if self._win_bash and not tools.get_env("CONAN_BASH_PATH"):
+            if not self.win_bash:
+                self.tool_requires("strawberryperl/5.30.0.1")
+            if not self.options.no_asm and not shutil.which("nasm"):
```
Comment (prince-chrismc) [inline recipes/openssl/1.x.x/conanfile.py:237]: should we always use the one from ConanCenter? Let the user override with a system version if they like?

**Review by prince-chrismc — COMMENTED** [review]
Just a quick pass before lunch :) I'll be focusing on this one now that boost was merged

File: recipes/openssl/1.x.x/conanfile.py (hunk 3 above)
Comment (System-Arch) [reply recipes/openssl/1.x.x/conanfile.py:234]: Hi @prince-chrismc,
From what I understand, old versions of openssl supported zlib-based compression. It was later determined to be a security vulnerability (e.g., https://www.cvedetails.com/bugtraq-bid/31692/OpenSSL-zlib-Compression-Memory-Leak-Remote-Denial-of-Serv.html) and hence support was dropped (see https://github.com/openssl/openssl/issues/14506). I'd personally opt for removing all support for versions less than 1.1.1 as use of older versions is unsupported and strongly discouraged (see https://www.openssl.org/source/). If CCI is okay with dropping support for those obsolete releases, I would happily rip out support for them from this recipe as it will make it much simpler.

Comment (prince-chrismc) [reply recipes/openssl/1.x.x/conanfile.py:234]: Sadly there's just so much demand for them. It's like old version of boost 🤷 They become a nightmare to maintain 🙊 

Thanks a ton for that extra info!

File: recipes/openssl/1.x.x/conanfile.py (hunk 5 above)
Comment (System-Arch) [reply recipes/openssl/1.x.x/conanfile.py:237]: Hi @prince-chrismc,
Please see the comment at lin 679, which predates my changes. It reads:
>            # enforce strawberry perl, otherwise wrong perl could be used (from Git bash, MSYS, etc.)
Thus I'm inclined to recommend leaving it as is for now. Let me know if you agree. Thanks

File: recipes/openssl/1.x.x/conanfile.py [hunk 6]
```diff
@@ -223,15 +216,13 @@ def config_options(self):
...
-            del self.options.fPIC
-        del self.settings.compiler.libcxx
-        del self.settings.compiler.cppstd
-
-    def layout(self):
-        pass
+            self.options.rm_safe("fPIC")
+        self.settings.rm_safe("compiler.libcxx")
+        self.settings.rm_safe("compiler.cppstd")
+        self.conf.define("tools.gnu:make_program", self._make_program)
```
Comment (prince-chrismc) [inline recipes/openssl/1.x.x/conanfile.py:222]: I asked the client experts about changing the conf, and the general advise is not to override the users input which is what should happen here.

In a future update I suspect we'll see a read only conf. The "define" functionality should be for the package info/conf info object to expose things in the package

Comment (prince-chrismc) [reply recipes/openssl/1.x.x/conanfile.py:222]:
```suggestion
```

File: recipes/openssl/1.x.x/conanfile.py (hunk 5 above)
Comment (prince-chrismc) [reply recipes/openssl/1.x.x/conanfile.py:237]: Sorry it was not clear in my comment but this was specifically related to `nasm` there's a reason why `tools.which` is deprecated and I wanted to double check with the rest of the team if we wanted to keep that functionality.

We'd like to removing this going forward, like build tools, these should be pulled from ConanCenter and end consumers can use the override mechanism to change that if they so wish.

What we'd like to see is

```suggestion
            if not self.options.no_asm:
```

File: recipes/openssl/1.x.x/conanfile.py [hunk 7]
```diff
@@ -535,27 +550,44 @@ def _configure_args(self):
...
+                if Version(conan_version).major < 2:
+                    zlib_info = self.deps_cpp_info["zlib"]
+                    include_path = zlib_info.include_paths[0]
+                    if self.settings.os == "Windows":
+                        lib_path = "%s/%s.lib" % (zlib_info.lib_paths[0], zlib_info.libs[0])
+                    else:
+                        lib_path = zlib_info.lib_paths[0]  # Just path, linux will find the right file
                 else:
-                    lib_path = zlib_info.lib_paths[0]  # Just path, linux will find the right file
+                    zlib_cpp_info = self.dependencies["zlib"].cpp_info
```
Comment (prince-chrismc) [inline recipes/openssl/1.x.x/conanfile.py:561]: So the `conan_version` is always something that catches attention, I brought this one up to the team and we discussed if this was the "current best approach" (obviously a moving target - what you did is absolutely correct 👍 we'd just like to set a baseline for others who come after)

This particular line should work in both 1.x and 2.0 - it should be use in the `generate()` save some files and then be read from the `build()` (this is ho the Toolchains` work for comparison)

We'd really love to see that approach used here in this case as well as we things it's the best solution

**Review by prince-chrismc — COMMENTED** [review]
This is some absolutely amazing work! The fact such an old recipe is working with both 1.x and 2.0 is a huge feat!

That being said, there's a lot of "bad smell" that we thing it's time to address. For example the usage of finding system tools is something we know is problematic. The usage of "find make" is definitely not what we want to be seeing with the `conf` options.

We know this would be a huge undertaking, so one of us (probably that noob @prince-chrismc) to almost start from scratch. However I do want your input on how'd you like to proceed.

I think we can go ahead with the merging this PR is the few new comments I have added are address but I absolutely do not mind taking this over in a much large refactor.

It's been years and even I am scared to touch this recipe but there are long standing issues like https://github.com/conan-io/conan-center-index/issues/3476 that I would love to give some attention

***

What would be a good next step for you? I would really like to continue with what you've done ❤️

File: recipes/openssl/1.x.x/conanfile.py (hunk 6 above)
Comment (System-Arch) [reply recipes/openssl/1.x.x/conanfile.py]: Hi @prince-chrismc,
I removed the above statement as part of a larger refactoring to call nmake explicitly rather than leveraging Autotools.make().

File: recipes/openssl/1.x.x/conanfile.py (hunk 7 above)
Comment (System-Arch) [reply recipes/openssl/1.x.x/conanfile.py]: Hi @prince-chrismc,
I implemented what I think you were suggesting here. Let me know if it is okay now.

File: recipes/openssl/1.x.x/conanfile.py [hunk 8]
```diff
@@ -267,6 +267,14 @@ def generate(self):
         gen_info["CXXFLAGS"] = tc.cxxflags
         gen_info["DEFINES"] = tc.defines
         gen_info["LDFLAGS"] = tc.ldflags
+        # Workaround lack of support for self.dependencies in build() method in Conan 1.x
```
Comment (prince-chrismc) [inline recipes/openssl/1.x.x/conanfile.py:270]:
```suggestion
        # Support for self.dependencies in build() method is currently restricted to `generate()` and `validate()`
        # See https://github.com/conan-io/conan/issues/12411 for more details 
```

File: recipes/openssl/1.x.x/conanfile.py [hunk 9]
```diff
@@ -728,35 +725,31 @@ def build(self):
...
+                        # NMAKE interprets trailing backslash as line continuation
+                        replace_in_file(self, self._nmake_makefile, 'INSTALLTOP=\\', 'INSTALLTOP=/')
+
+                        self.run(f'nmake /F {self._nmake_makefile}')
   
-    @property
-    def _make_program(self):
-        if self._use_nmake:
-            return "nmake"
-        make_program = os.getenv("CONAN_MAKE_PROGRAM") or shutil.which("make") or shutil.which('mingw32-make')
```
Comment (prince-chrismc) [inline recipes/openssl/1.x.x/conanfile.py]: 👍  for future readers, this is replaced by the conf `tools.gnu:make_program` https://docs.conan.io/en/latest/reference/config_files/global_conf.html?highlight=make%20program#tools-configurations with the new generators

File: recipes/openssl/1.x.x/test_package/digest.c [hunk 10]
```diff
@@ -7,7 +7,7 @@
 #include <openssl/crypto.h>
 #include <openssl/ssl.h>
 #if defined(WITH_ZLIB)
-#include <zlib.h>
```
Comment (prince-chrismc) [inline recipes/openssl/1.x.x/test_package/digest.c:10]: This is needed as in 2.0 the graph does not expose transitive header or libs which is why the feature test through openssl is required

File: recipes/openssl/1.x.x/conanfile.py [hunk 11]
```diff
@@ -1,22 +1,28 @@
...
+from conan.tools.apple import is_apple_os, XCRun
+from conan.tools.scm import Version
+from conan.errors import ConanInvalidConfiguration
+from conan.tools.files import chdir, copy, rename, rmdir, load, save, get, apply_conandata_patches, export_conandata_patches, replace_in_file
 from contextlib import contextmanager
 from functools import total_ordering
 import fnmatch
+import json
 import os
+import shutil
```
Comment (prince-chrismc) [inline recipes/openssl/1.x.x/conanfile.py:16]: Linter

```suggestion
```

File: recipes/openssl/1.x.x/conanfile.py [hunk 12]
```diff
@@ -241,17 +232,53 @@ def validate(self):
 
     def build_requirements(self):
         if self._settings_build.os == "Windows":
-            if not self._win_bash:
-                self.build_requires("strawberryperl/5.30.0.1")
-            if not self.options.no_asm and not tools.which("nasm"):
-                self.build_requires("nasm/2.15.05")
-        if self._win_bash and not tools.get_env("CONAN_BASH_PATH"):
+            if not self.win_bash:
```
Comment (prince-chrismc) [inline recipes/openssl/1.x.x/conanfile.py:235]: This is the new way for future readers https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html?highlight=win_bash#windows-subsystems

File: recipes/openssl/1.x.x/conanfile.py [hunk 13]
```diff
@@ -241,17 +232,53 @@ def validate(self):
...
+
     def source(self):
         get(self, **self.conan_data["sources"][self.version],
-            destination=self._source_subfolder, strip_root=True)
-
+            destination=self.source_folder, strip_root=True)
+
+    def generate(self):
+        tc = AutotoolsToolchain(self)
+        # workaround for random error: size too large (archive member extends past the end of the file)
```
Comment (prince-chrismc) [inline recipes/openssl/1.x.x/conanfile.py:251]: old code, just moved https://github.com/conan-io/conan-center-index/pull/14066/files#diff-d67d36ebb633f3e920a34cd24c6c92ac12ab88b1f1db0a694841133faeb10fe5L652-L662

File: recipes/openssl/1.x.x/conanfile.py [hunk 14]
```diff
@@ -447,58 +474,51 @@ def _tool(self, env_name, apple_name):
...
     def _configure_args(self):
         openssldir = self.options.openssldir or self._get_default_openssl_dir()
-        prefix = tools.unix_path(self.package_folder) if self._win_bash else self.package_folder
-        openssldir = tools.unix_path(openssldir) if self._win_bash else openssldir
+        openssldir = unix_path(self, openssldir) if self.win_bash else openssldir
         args = [
           '"%s"' % (self._target if self._full_version >= "1.1.0" else self._ancestor_target),
           "shared" if self.options.shared else "no-shared",
-                "--prefix=\"%s\"" % prefix,
+                "--prefix=/",
```
Comment (prince-chrismc) [inline recipes/openssl/1.x.x/conanfile.py:521]: This jumped out at me, this was the package folder but now it's just root 🤔 Is the new Autotools install doing a better job?

**Review by prince-chrismc — COMMENTED** [review]
Perfect this address a bunch of the the questions/suggestions/concerns! There's a lot less code smell ❤️ 

I have one technical questions https://github.com/conan-io/conan-center-index/pull/14066/files#r1052713668 and one tiny nit about a comment https://github.com/conan-io/conan-center-index/pull/14066/files#r1052707402

Overall it looks super good, just want to make sure I understand the changes

File: recipes/openssl/1.x.x/conanfile.py (hunk 14 above)
Comment (System-Arch) [reply recipes/openssl/1.x.x/conanfile.py:522]: Hi @prince-chrismc,.
It is my understanding that in Conan 2.,0 self.package_folder is determined dynamically in the export() method and is not known when the generate() or build() methods are called. This is the pattern I have been using to permit build artifacts to be relocated at export-pkg time. Let me know if I am missing anything. Thanks.

File: recipes/openssl/1.x.x/test_package/digest.c (hunk 10 above)
Comment (System-Arch) [reply recipes/openssl/1.x.x/test_package/digest.c:10]: Hi @prince-chrismc,
The original test here did not actually validate that OpenSSL was built with zlib functionality. I revised the test to confirm that the zlib support was present in OpenSSL. This support does not require client access to the zlib header file. Let me know if you have any questions or concerns. Thanks

**Review by prince-chrismc — APPROVED** [review]

**Review by czoido — APPROVED** [review]

File: recipes/openssl/1.x.x/conanfile.py [hunk 15]
```diff
@@ -241,17 +231,54 @@ def validate(self):
...
-                self.build_requires("strawberryperl/5.30.0.1")
-            if not self.options.no_asm and not tools.which("nasm"):
-                self.build_requires("nasm/2.15.05")
-        if self._win_bash and not tools.get_env("CONAN_BASH_PATH"):
+            if not self.win_bash:
+                self.tool_requires("strawberryperl/5.30.0.1")
+            if not self.options.no_asm:
+                self.tool_requires("nasm/2.15.05")
+        if self.win_bash and not os.getenv("CONAN_BASH_PATH") and not self._use_nmake:
             self.build_requires("msys2/cci.latest")
```
Comment (SpaceIm) [inline recipes/openssl/1.x.x/conanfile.py:239]: I've not tested but I'm pretty sure it breaks MinGW. There is a confusion here about `self.win_bash`, it's not something set externally.

Comment (SpaceIm) [reply recipes/openssl/1.x.x/conanfile.py:239]: I confirm, it's broken:

```
> conan install openssl/1.1.1s@ -o openssl:shared=True -pr:b win-x86_64-gcc12 -pr:h win-x86_64-gcc12 -b missing
Configuration (profile_host):
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
compiler.version=12
os=Windows
[options]
openssl:shared=True
[build_requires]
[env]
CC=D:/mingw64/bin/gcc.exe
CXX=D:/mingw64/bin/g++.exe
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
tools.build:compiler_executables={'c': 'D:/mingw64/bin/gcc.exe', 'cpp': 'D:/mingw64/bin/gcc.exe'}
[buildenv]
CC=D:/mingw64/bin/gcc.exe
CXX=D:/mingw64/bin/g++.exe

Configuration (profile_build):
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
compiler.version=12
os=Windows
[options]
openssl:shared=True
[build_requires]
[env]
CC=D:/mingw64/bin/gcc.exe
CXX=D:/mingw64/bin/g++.exe
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
tools.build:compiler_executables={'c': 'D:/mingw64/bin/gcc.exe', 'cpp': 'D:/mingw64/bin/gcc.exe'}
[buildenv]
CC=D:/mingw64/bin/gcc.exe
CXX=D:/mingw64/bin/g++.exe

openssl/1.1.1s: Not found in local cache, looking in remotes...
openssl/1.1.1s: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.18k]
Downloading conanfile.py completed [41.44k]
Downloading conan_export.tgz completed [0.33k]
Decompressing conan_export.tgz completed [0.00k]
openssl/1.1.1s: Downloaded recipe revision c5843f5e0776c9e862e08c911cd09958
strawberryperl/5.30.0.1: Not found in local cache, looking in remotes...
strawberryperl/5.30.0.1: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.10k]
Downloading conanfile.py completed [2.25k]
Downloading conan_export.tgz completed [0.31k]
Decompressing conan_export.tgz completed [0.00k]
strawberryperl/5.30.0.1: Downloaded recipe revision d125df083747d815c66e9ee621f3909f
nasm/2.15.05: Not found in local cache, looking in remotes...
nasm/2.15.05: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.22k]
Downloading conanfile.py completed [4.04k]
Downloading conan_export.tgz completed [0.31k]
Decompressing conan_export.tgz completed [0.00k]
nasm/2.15.05: Downloaded recipe revision c13d1db156147946c9aae400891b4baa
Installing package: openssl/1.1.1s
Requirements
    openssl/1.1.1s from 'conancenter' - Downloaded
Packages
    openssl/1.1.1s:bb11550f8236e219d08dd4d948c91d66592f7318 - Build
Build requirements
    nasm/2.15.05 from 'conancenter' - Downloaded
    strawberryperl/5.30.0.1 from 'conancenter' - Downloaded
Build requirements packages
    nasm/2.15.05:0a420ff5c47119e668867cdb51baff0eca1fdb68 - Download
    strawberryperl/5.30.0.1:ca33edce272a279b24f87dc0d4cf5bbdcffbc187 - Download

Installing (downloading, building) binaries...
nasm/2.15.05: Retrieving package 0a420ff5c47119e668867cdb51baff0eca1fdb68 from remote 'conancenter'
Downloading conanmanifest.txt completed [0.73k]
Downloading conaninfo.txt completed [0.32k]
Downloading conan_package.tgz completed [2044.13k]
Decompressing conan_package.tgz completed [0.00k]
nasm/2.15.05: Package installed 0a420ff5c47119e668867cdb51baff0eca1fdb68
nasm/2.15.05: Downloaded package revision 801ea6b6d3c17d507832dc2f9c17b6b8
strawberryperl/5.30.0.1: Retrieving package ca33edce272a279b24f87dc0d4cf5bbdcffbc187 from remote 'conancenter'
Downloading conanmanifest.txt completed [483.04k]
Downloading conaninfo.txt completed [0.30k]
Downloading conan_package.tgz completed [32402.67k]
Decompressing conan_package.tgz completed [0.00k]
strawberryperl/5.30.0.1: Package installed ca33edce272a279b24f87dc0d4cf5bbdcffbc187
strawberryperl/5.30.0.1: Downloaded package revision ffd124eb48d535d9e5b7134311ef0b65
openssl/1.1.1s: Applying build-requirement: strawberryperl/5.30.0.1
openssl/1.1.1s: Applying build-requirement: nasm/2.15.05
Downloading conan_sources.tgz completed [0.41k]
Decompressing conan_sources.tgz completed [0.00k]
[HOOK - conan-center.py] pre_source(): [IMMUTABLE SOURCES (KB-H010)] OK
openssl/1.1.1s: Configuring sources in C:\Users\spaceim\.conan\data\openssl\1.1.1s\_\_\source\src
Downloading openssl-1.1.1s.tar.gz completed [9637.68k]                                   openssl/1.1.1s: enssl/1.1.1s:
openssl/1.1.1s:
[HOOK - conan-center.py] post_source(): [LIBCXX MANAGEMENT (KB-H011)] OK
[HOOK - conan-center.py] post_source(): [CPPSTD MANAGEMENT (KB-H022)] OK
[HOOK - conan-center.py] post_source(): [SHORT_PATHS USAGE (KB-H066)] OK
openssl/1.1.1s: Copying sources to build folder
openssl/1.1.1s: Building your package in C:\Users\spaceim\.conan\data\openssl\1.1.1s\_\_\build\bb11550f8236e219d08dd4d948c91d66592f7318
openssl/1.1.1s: Generator txt created conanbuildinfo.txt
openssl/1.1.1s: Calling generate()
openssl/1.1.1s: Aggregating env generators
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] 'fPIC' option not found
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] OK
openssl/1.1.1s: Calling build()
openssl/1.1.1s: Apply patch (portability): TVOS and WatchOS don't like fork()
openssl/1.1.1s: gen_info = {'CFLAGS': ['-m64', '-O3'], 'CXXFLAGS': ['-m64', '-O3'], 'DEFINES': ['NDEBUG'], 'LDFLAGS': ['-m64']}
openssl/1.1.1s: using target: mingw-conan-Release-Windows-x86_64-gcc-12 -> mingw64
openssl/1.1.1s: my %targets = (
    "mingw-conan-Release-Windows-x86_64-gcc-12" => {
        inherit_from => [ "mingw64" ],
        cflags => add("-m64 -O3"),
        cxxflags => add("-m64 -O3"),
        defines => add(["NDEBUG"]),
        includes => add(),
        lflags => add("-m64"),



        cc => "D:/mingw64/bin/gcc.exe",
        cxx => "D:/mingw64/bin/g++.exe",



    },
);

openssl/1.1.1s: activated option: shared
openssl/1.1.1s: activated option: shared
openssl/1.1.1s: ['"mingw-conan-Release-Windows-x86_64-gcc-12"', 'shared', '--prefix=/', '--openssldir="res"', 'no-unit-test', 'threads', 'PERL=C:\\Users\\spaceim\\.conan\\data\\strawberryperl\\5.30.0.1\\_\\_\\package\\ca33edce272a279b24f87dc0d4cf5bbdcffbc187\\bin\\perl.exe', 'no-tests', '--release', 'no-md2', 'shared']
Configuring OpenSSL version 1.1.1s (0x1010113fL) for mingw-conan-Release-Windows-x86_64-gcc-12
Using os-specific seed configuration

******************************************************************************
This perl implementation doesn't produce Unix like paths (with forward slash
directory separators).  Please use an implementation that matches your
building platform.

This Perl version: 5.30.0 for MSWin32-x64-multi-thread
******************************************************************************
openssl/1.1.1s:
openssl/1.1.1s: ERROR: Package 'bb11550f8236e219d08dd4d948c91d66592f7318' build failed
openssl/1.1.1s: WARN: Build folder C:\Users\spaceim\.conan\data\openssl\1.1.1s\_\_\build\bb11550f8236e219d08dd4d948c91d66592f7318\build-release
ERROR: openssl/1.1.1s: Error in build() method, line 724
        self.run(f'{self._perl} ./Configure {args}')
        ConanException: Error 255 while executing C:\Users\spaceim\.conan\data\strawberryperl\5.30.0.1\_\_\package\ca33edce272a279b24f87dc0d4cf5bbdcffbc187\bin\perl.exe ./Configure "mingw-conan-Release-Windows-x86_64-gcc-12" shared --prefix=/ --openssldir="res" no-unit-test threads PERL=C:\Users\spaceim\.conan\data\strawberryperl\5.30.0.1\_\_\package\ca33edce272a279b24f87dc0d4cf5bbdcffbc187\bin\perl.exe no-tests --release no-md2 shared
```

Comment (System-Arch) [reply recipes/openssl/1.x.x/conanfile.py:239]: Hi @SpaceIm,
Sorry for breaking this. As you note, I had misunderstood the Conan 2.0 adoption of win_bash. Thanks for fixing it.
