### ISSUE TITLE
[package] crashpad/cci.20220219: Unable to build in Ubuntu 22.04 x86_64 (in Docker)

### ISSUE THREAD

**Issue by DronCode** [conan-io/conan-center-index#27740]
### Description

Hi! I'm trying to use `crashpad/cci.20220219` in my application, but I encounter a compile-time error on Linux (x86_64, Ubuntu 22.04 in Docker):
```
In file included from ../../third_party/mini_chromium/mini_chromium/base/atomicops.h:170:
../../third_party/mini_chromium/mini_chromium/base/atomicops_internals_portable.h:57:25: error: cannot initialize a parameter of type 'int' with an lvalue of type 'const memory_order'
   57 |   __atomic_thread_fence(std::memory_order_seq_cst);
```

This issue has already been addressed in [this vcpkg PR](https://github.com/microsoft/vcpkg/pull/39671), and I'm trying to apply the same fix locally via Conan. 
However, I ran into a problem: I attempted to create a local "proxy" package that depends on the original crashpad and patches it in the build() method, but Conan does not allow accessing the source directory of another package (e.g., crashpad_dep.source_folder). This results in a ConanFileInterface error.

Is there a supported way in Conan 2 to locally patch a recipe from ConanCenter without fully forking it?
Or perhaps a recommended way to override a package with patches cleanly within a project or CI context?

My current patch (maybe it's useful)
```
--- third_party/mini_chromium/mini_chromium/base/atomicops_internals_portable.h	2022-01-25 07:27:16
+++ third_party/mini_chromium/mini_chromium/base/atomicops_internals_portable.h	2025-06-19 20:34:39
@@ -51,13 +51,7 @@
               "incompatible 32-bit atomic layout");
 
 inline void MemoryBarrier() {
-#if defined(__GLIBCXX__)
-  // Work around libstdc++ bug 51038 where atomic_thread_fence was declared but
-  // not defined, leading to the linker complaining about undefined references.
-  __atomic_thread_fence(std::memory_order_seq_cst);
-#else
   std::atomic_thread_fence(std::memory_order_seq_cst);
-#endif
 }
 
 inline Atomic32 NoBarrier_CompareAndSwap(volatile Atomic32* ptr,

--- util/misc/uuid.cc	2022-02-17 22:33:24
+++ util/misc/uuid.cc	2025-06-19 20:37:27
@@ -38,7 +38,7 @@
 namespace crashpad {

 static_assert(sizeof(UUID) == 16, "UUID must be 16 bytes");
-static_assert(std::is_pod<UUID>::value, "UUID must be POD");
+//static_assert(std::is_pod<UUID>::value, "UUID must be POD");

 bool UUID::operator==(const UUID& that) const {
   return memcmp(this, &that, sizeof(*this)) == 0;
```

### Package and Environment Details

* Package Name/Version: **crashpad/cci.20220219**
* Operating System+version: **Linux Ubuntu 22.04**
* Compiler+version: **Clang 20, GCC**
* Docker image: **ubuntu:22.04**
* Conan version: **conan 1.18.0**
* Python version: **Python 3.7.4**

### Conan profile

[settings]
os=Macos
os_build=Macos
arch=armv8
arch_build=armv8
compiler=apple-clang
compiler.version=14
compiler.libcxx=libc++
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

Try to build dependency `crashpad/cci.20220219` in Ubuntu 22.04 

### Logs

<details><summary>Click to expand log</summary>

```
Put your log output here
```

</details>

**Comment by jcar87** [comment]
> Is there a supported way in Conan 2 to locally patch a recipe from ConanCenter without fully forking it?
> Or perhaps a recommended way to override a package with patches cleanly within a project or CI context?

You may have find the following useful:
https://docs.conan.io/2/reference/tools/files/patches.html#core-sources-patch-extra-path

You'd have to clone the repository to locally export the recipe or create the package, but would not need a fork.
