### ISSUE TITLE
[package] google-cloud-cpp/1.40.1: Doesn't compile

### ISSUE THREAD

**Issue by jjcasmar** [conan-io/conan-center-index#12295]
### Package and Environment Details

* Package Name/Version: **google-cloud-cpp/1.40.1**
* Operating System+version: **Archlinux**
* Compiler+version: **GCC 10**
* Conan version: **conan 1.51.2**
* Python version: **Python 3.8.10**

### Conan profile

```Configuration for profile test:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]```

### Steps to reproduce

_No response_

### Logs

google-cloud-cpp doesn't compile with protobuf version 3.21.4 (grpc), which is needed because its dependencies need it. 

```[ 48%] Building CXX object source_subfolder/external/googleapis/CMakeFiles/google_cloud_cpp_logging_protos.dir/google/logging/v2/logging_metrics.pb.cc.o
/home/vscode/.conan/data/google-cloud-cpp/1.40.1/_/_/build/b5710c2c5d2dd070121c362981eeffbffec200d6/source_subfolder/generator/internal/descriptor_utils.cc:39:10: fatal error: google/protobuf/compiler/
cpp/cpp_names.h: No such file or directory
   39 | #include <google/protobuf/compiler/cpp/cpp_names.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [source_subfolder/generator/CMakeFiles/google_cloud_cpp_generator.dir/build.make:160: source_subfolder/generator/CMakeFiles/google_cloud_cpp_generator.dir/internal/descriptor_utils.cc.o] E
rror 1```

**Comment by coryan** [comment]
Hmmm... Most application developers should not need to compile `google-cloud-cpp/generator`.  It is a tool to generate code in `google/cloud/*`.  In fact, the default is to disable it.  I think the problem is here:

https://github.com/conan-io/conan-center-index/blob/7587042fb02e9496aa6c6677c1144aa9cbfc845f/recipes/google-cloud-cpp/all/conanfile.py#L99

**Comment by coryan** [comment]
Consider updating to the 2.x series.
