### ISSUE TITLE
[package] z3/4.13.0 fails to build

### ISSUE THREAD

**Issue by rdong8** [conan-io/conan-center-index#29423]
### Description

I was running into errors with the llvm-core package and it seems like z3 is what is failing to compile. I can't get it to work with any of C++17-26 and GCC 15.2.0, Clang 21.1.8.

### Package and Environment Details

* Package Name/Version: **z3/4.13.0**
* Operating System+version: **Linux Ubuntu 24.04**
* Compiler+version: **GCC 15.2.0, Clang 21.1.8**
* Docker image:
* Conan version: **conan 2.24.0**
* Python version: **Python 3.12.3**

### Conan profile

Profile 1:

```ini
[conf]
tools.build:compiler_executables={'c': 'clang-21', 'cpp': 'clang++-21'}
tools.cmake.cmaketoolchain:generator=Ninja Multi-Config

[settings]
arch=x86_64
compiler=clang
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=21
os=Linux
```

Profile 2:

```ini
[conf]
tools.build:compiler_executables={'c': 'gcc-15.2.0', 'cpp': 'g++-15.2.0'}
tools.cmake.cmaketoolchain:generator=Ninja Multi-Config

[settings]
arch=x86_64
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=15
os=Linux
```

### Steps to reproduce

```
conan install -b missing -pr:h=host --output-folder=build -s build_type=Release -s '&':build_type=Debug
```

### Logs

[Profile 1](https://github.com/user-attachments/files/24814395/clang21cpp20.log)
[Profile 2](https://github.com/user-attachments/files/24814396/gcc15cpp20.log)

**Comment by uilianries** [comment]
@rdong8 Hello! Your report it seems be duplicated to #27193:

> /u4/rydong/.conan2/p/b/z363f6690612fe8/b/src/src/math/lp/column_info.h:50:58: error: no member named 'm_low_bound' in 'column_info<T>'
   50 |             (!m_lower_bound_is_set || m_lower_bound == c.m_low_bound) &&

Please, update the Conan package for Z3 to the latest version available in Conan Center and try to build it again:

    conan install -r conancenter --update --requires="z3/[*]"

Feel free to share your feedback. Regards. 

## EDIT:

As you are using `llvm-core` as a dependency, it will require `z3/4.13.0` always. You will need to update your llvm-core recipe to use a newer version of `z3` in order to fix it.

There are 2 ways to do that:

* You can use [replace_requires](https://docs.conan.io/2/reference/config_files/profiles.html#replace-requires) feature in your Conan profile to configure z3 version:

```ini
# ~/.conan2/profiles/default

[replace_requires]
z3/*: z3/4.15.4
```

It will mark use `z3/4.15.4` (latest) always instead of any other version. You will need to re-build you llvm-core Conan package as well to consume altogether.

* In case you don't need z3 support in LLVM Core, you just can just disable it from your dependencies graph by using the `with_z3` option available in llvm-core package:

    conan install -r conancenter --update --requires=llvm-core/19.1.7 -o "&:with_z3=False"

The `&:with_z3=False` tells to disable z3 only for llvm-core, it should not add z3 in your graph.

Regards.

**Comment by rdong8** [comment]
Thanks! Turning off z3 seems to get past this error.
