### PR TITLE
restinio: bump deps + modernize

### PR DESCRIPTION
**Pull request by prince-chrismc**
Specify library name and version:  **lib/1.0**

This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!

Just an everyday consumer

---

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Review by garethsb — APPROVED** [review]

**Review by madebr — APPROVED** [review]

**Review by SSE4 — APPROVED** [review]

**Review by ericLemanissier — APPROVED** [review]

**Comment by kjetilj** [comment]
Upgrading to fmt/8.0.1 breaks this package, no longer compiles with GCC as the format strings has to be constexpr or wrapped in fmt::runtime.

**Comment by uilianries** [comment]
@kjetilj Please, open an issue reporting your error with details, including your profile and package version, steps to reproduce and log. This PR was tested using different GCC versions, from 5 to 10, and passed by all them.

**Comment by kjetilj** [comment]
Sorry, I am not familiar enough with these packages or conan to create a repro, but I can provide some more details.

It will fail with c++20 and gcc (and possibly clang), due to format now requiring the format to be parsed at compile time (https://github.com/fmtlib/fmt/releases/tag/8.0.0). 

If we look at restinio it will fail to compiler here:
https://github.com/Stiffstream/restinio/blob/0052518f5692f8f051031e06d933b726191be97e/dev/restinio/message_builders.hpp#L822
format_string is not constexpr, and it changes at runtime, and that piece of code would have to be rewritten to fmt::runtime(format_string) to work with fmt/8.0.1

I also observed some additional compilation errors, but that one was the most obvious where the API of 8.0.1 is not compatible.

**Comment by prince-chrismc** [comment]
😕 

You can see my pet project running this recipe revision https://github.com/prince-chrismc/user-management/commit/bf5012d22afffb99d5df3f03a406b40dda8ec8a9#diff-10e08a419e850eba1ebba18fdd28eb7ec1b7e8baa9bcc3b973e2b8891ec726be

I have never tried to build with C++20 enabled

**Comment by uilianries** [comment]
@kjetilj please, open an issue. PRs were made for patch, not discussion. This thread will be lost if followed in a PR. Besides that, this PR is closed, which means, it don't have visibility if someone is looking for the same error.

**Comment by kjetilj** [comment]
ok, I did my best here:
https://github.com/conan-io/conan-center-index/issues/7448

**Comment by uilianries** [comment]
thank you!
