### PR TITLE
onnxruntime: fix the windows compiler.cppstd=20 and cuda builds

### PR DESCRIPTION
**Pull request by sbreuss**
### Summary
Changes to recipe:  **onnxruntime/1.24.4**

#### Details

- Fixes the windows build using Visual Studio 2022 and compiler.cppstd=20
- Fix build issue with log macro and wchar_t
- Fix build issues with cuda > 13

---
- [x] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x] If this is a bug fix, please link related issue or provide bug details
- [x] Tested locally with at least one configuration using a recent version of Conan

---
Add a :+1: reaction to pull requests you find [important](https://github.com/conan-io/conan-center-index/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc) to help the team prioritize, thanks!

### CODE REVIEW

**Comment by flamxi** [comment]
latest conan version of onnxunrtime (v1.23.2) when built with_cuda=True, it shows me this error in linux: 

CMake Error at external/cudnn_frontend.cmake:2 (onnxruntime_fetchcontent_declare):
  Unknown CMake command "onnxruntime_fetchcontent_declare".
Call Stack (most recent call first):
  onnxruntime_providers_cuda.cmake:232 (include)
  onnxruntime_providers_cuda.cmake:318 (config_cuda_provider_shared_module)
  onnxruntime_providers.cmake:122 (include)
  CMakeLists.txt:1682 (include)
  
 I was hopping maybe you can tackle this one as well?!

**Comment by sbreuss** [comment]
I just fixed the cuda build on linux. CuDNN support is currently disabled (onnxruntime_CUDA_MINIMAL) because the library https://github.com/NVIDIA/cudnn-frontend would need to be packaged to enable cudnn within onnxruntime.

**Comment by sbreuss** [comment]
I don't know if it is ok to add a header only package for the cudnn-frontend package to support onnxruntime builds with cudnn support. If not, feel free to revert the last commit.

File: recipes/onnxruntime/all/cmake/onnxruntime_external_deps.cmake [hunk 1]
```diff
@@ -104,3 +121,8 @@ set(onnxruntime_EXTERNAL_LIBRARIES ${onnxruntime_EXTERNAL_LIBRARIES_XNNPACK} ${W
 
 file(TO_NATIVE_PATH ${CMAKE_BINARY_DIR}  ORT_BINARY_DIR)
 file(TO_NATIVE_PATH ${PROJECT_SOURCE_DIR}  ORT_SOURCE_DIR)
+
+if(NOT onnxruntime_EXTERNAL_DEPENDENCIES)
+  add_custom_target(onnxruntime_empty_dummy)
+  set(onnxruntime_EXTERNAL_DEPENDENCIES onnxruntime_empty_dummy)
+endif()
```
Comment (franramirez688) [inline recipes/onnxruntime/all/cmake/onnxruntime_external_deps.cmake]: There was a bug in previous recipe revisions; this should be solved now.

```suggestion
```

File: recipes/onnxruntime/all/cmake/onnxruntime_external_deps.cmake [hunk 2]
```diff
@@ -91,6 +93,21 @@ if (onnxruntime_USE_XNNPACK)
...
+  # cuDNN is not needed for minimal CUDA builds (e.g., TensorRT-only builds)
+  if(NOT onnxruntime_CUDA_MINIMAL)
+    if(onnxruntime_CUDNN_HOME)
+      file(TO_CMAKE_PATH ${onnxruntime_CUDNN_HOME} onnxruntime_CUDNN_HOME)
+      set(CUDNN_PATH ${onnxruntime_CUDNN_HOME})
+    endif()
+
+    include(cuDNN)
+  endif()
+endif()
```
Comment (franramirez688) [inline recipes/onnxruntime/all/cmake/onnxruntime_external_deps.cmake:104]: I recommend splitting all the CUDA proposal in a new PR.

File: recipes/onnxruntime/all/patches/cmake-cxx-standard.patch [hunk 3]
```diff
@@ -1,15 +1,18 @@
...
--else()
--set(CMAKE_CXX_STANDARD 17)
+-if (NOT CMAKE_CXX_STANDARD)
+-  # TODO: update this once all system adapt c++20
+-  if (CMAKE_SYSTEM_NAME STREQUAL "Darwin")
+-    set(CMAKE_CXX_STANDARD 20)
+-  else()
+-    set(CMAKE_CXX_STANDARD 17)
+-  endif()
 -endif()
```
Comment (franramirez688) [inline recipes/onnxruntime/all/patches/cmake-cxx-standard.patch]: We do not need to patch this anymore as it's under the `if (NOT CMAKE_CXX_STANDARD)` check

**Review by franramirez688 — COMMENTED** [review]
Hi @sbreuss 

Thanks a lot for contributing 🙏 

I put some comments, but as a general note before moving this forward, please, let's split the PR:

* Keep this one with the minimal changes to add the new 1.24.2 version.
* Open another PR proposing the fix for CUDA and Windows, and upload some successful build logs verifying the changes from your local environment.

Thanks a lot!

**Comment by sbreuss** [comment]
I made the cuda changes minimal and removed the cudnn frontend package. I also updated to the latest onnxruntime 1.24.3 and fixed the build with cuda 13.1 using changes from https://github.com/microsoft/onnxruntime/commit/ca89287f3b6623e980df96b54c39d67eb7f2d050

**Comment by franramirez688** [comment]
Hi @sbreuss 

Could you rebase from the master branch? As it was ORT updated recently, we can keep this PR only dedicated to the Windows CUDA fix 🙏 Thanks!

Sorry for any inconvenience!

**Review by franramirez688 — COMMENTED** [review]
Hi @sbreuss,

Thanks again for this PR! I just helped to update your branch with the master one.

Are those new patches reported upstream or anywhere? I'm trying to understand the whole context about why they're needed. Any reference or explanation is more than welcome. Also, any chance of having logs about the failed/successful logs?

**Comment by sbreuss** [comment]
I tried to reproduce our initial test case that failed, and I think it has to do with our profile using the c++ 20 as standard in combination with our internally used versions and building everything from recipies only. When using c++ 17 I can build the default onnxruntime cpu package without the patches for logging and the empty EXTERNAL_DEPENDENCIES.

```
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=20
compiler.runtime=dynamic
compiler.version=194
os=Windows

[conf]
tools.cmake.cmaketoolchain:generator=Ninja
```

When using this as my default profile, I can reproduce the build error with the wchar logging.

```
C:\Users\simon\.conan2\p\b\onnxre52f469884384\b\src\onnxruntime\core\session\utils.cc(552): error C2280: 'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,const wchar_t *)': attempting to reference a deleted function
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\include\__msvc_ostream.hpp(972): note: see declaration of 'std::operator <<'
C:\Users\simon\.conan2\p\b\onnxre52f469884384\b\src\onnxruntime\core\session\utils.cc(552): error C2088: built-in operator '<<' cannot be applied to an operand of type 'std::basic_ostream<char,std::char_traits<char>>'
```

I did not report this issue upstream or anywhere else. I can also run some more tests for the cuda patches using compiler.cppstd=17 as default, but I guess that they are needed. 

What is the current "default" c++ profile that is expected to work, and how should I deal with the issue regarding compiler.cppstd=20?

**Comment by sbreuss** [comment]
are there any news on this?

**Comment by franramirez688** [comment]
Hi @sbreuss 

Sorry for the delay 🙏 

Whenever we find an upstream bug, we check that it's already reported in the official repository and hopefully fixed. Once that fix is merged, it's time to bring it back over here.

Regarding the default cppstd, our CCI normally starts trying C++17 for all the OSs, but obviously depends on the minimum required cppstd version.

In summary, the next steps:

* Let's check if this bug is reported in the ONNXRUNTIME repository.
   * If not, we should open an issue referring to your environment context and logs.
   * If yes, we would need to backport the fix over here (your `recipes/onnxruntime/all/patches/fix-logging-ortchar.patch`).

Also, as I see that there are more changes apart from the proposed patch, I'd like to understand better this:

* Without all these changes, the CUDA builds run OK in Windows and C++17?
* Are all these changes related to CUDA + C++20?

I'm asking because if there is more than one fix here, we could split the PR into several ones to avoid blocking any bugfix related to Cuda + Conan.

**Comment by franramirez688** [comment]
Hi @sbreuss, do you have any updates on this from my previous [comment](https://github.com/conan-io/conan-center-index/pull/29641#issuecomment-4222732211)?

**Comment by franramirez688** [comment]
Closing this PR for now 🙏 

Please, do not hesitate to reopen this or open a new one, and check my previous comment https://github.com/conan-io/conan-center-index/pull/29641#issuecomment-4222732211. There are still open questions we need to clarify.

Thanks a lot!
