### PR TITLE
MPC Conan 2.0 Compatibility

### LINKED ISSUE #14768: [package] MPC/1.2.0 lacks support for Conan 2.0
### Description

mpc has yet to be ported to Conan 2.0

### Package and Environment Details

Package Name/Version: mpc/1.2.0
Operating System+version: Debian 10
Compiler+version: gcc 8
Conan version: conan 2.0.0-beta6
Python version: Python 3.7.3

### Conan profile

Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
[options]
cmake*:bootstrap=True
[tool_requires]
!openssl*: cmake/3.24.2

### Steps to reproduce

conan-2.0 build -pr:b tools.jinja -pr:h tools.jinja --name mpc--version 1.2.0 .

### Logs

<details><summary>Click to expand log</summary>

```
conan-2.0 source --name mpc --version 1.2.0 .
ERROR: Error loading conanfile at '/tmp/tmp.R02tApJCqY/mpc/conanfile.py': Unable to load conanfile in /tmp/tmp.R02tApJCqY/mpc/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmp.R02tApJCqY/mpc/conanfile.py", line 1, in <module>
    from conans import ConanFile, AutoToolsBuildEnvironment, tools
ImportError: cannot import name 'ConanFile' from 'conans' (/mathworks/devel/sandbox/marc/conan-2.0/conan-io/conans/__init__.py)```

</details>

### PR DESCRIPTION
**Pull request by System-Arch**
Specify library name and version:  **mpc/1.2.0**

Migrated recipe to Conan 2.0. Resolves #14768. Note that these changes are untested on Windows with Conan 2.0 because some of the required dependencies don't build with 2.0 yet

---

- [X] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [X] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

File: recipes/mpc/all/conanfile.py [hunk 1]
```diff
@@ -16,65 +23,79 @@ class MpcConan(ConanFile):
...
 
     def build(self):
-        for patch in self.conan_data.get("patches", {}).get(self.version, []):
-            tools.patch(**patch)
-        autotools = self._configure_autotools()
+        apply_conandata_patches(self)
+        with chdir(self, self.source_folder):
+            if not os.path.exists("configure"):
+                command = "autoreconf -i"
+                self.run(command)
```
Comment (StellaSmith) [inline recipes/mpc/all/conanfile.py:84]: The `Autotool` helper has an `.autoreconf()` method.
https://docs.conan.io/en/2.0/reference/tools/gnu/autotools.html#conan.tools.gnu.autotools.Autotools.autoreconf

File: recipes/mpc/all/conanfile.py [hunk 2]
```diff
@@ -16,65 +23,78 @@ class MpcConan(ConanFile):
...
-        if self._autotools:
-            return self._autotools
-        self._autotools = AutoToolsBuildEnvironment(self, win_bash=tools.os_info.is_windows)
-        args = []
+        tc = AutotoolsToolchain(self)
+        tc.configure_args.append(f'--with-gmp={unix_path(self, self.dependencies["gmp"].package_folder)}')
+        tc.configure_args.append(f'--with-mpfr={unix_path(self, self.dependencies["mpfr"].package_folder)}')
         if self.options.shared:
-            args.extend(["--disable-static", "--enable-shared"])
+            tc.configure_args.extend(["--disable-static", "--enable-shared"])
```
Comment (Hopobcn) [inline recipes/mpc/all/conanfile.py:71]: This "should" not be required. According to  https://docs.conan.io/en/2.0/reference/tools/gnu/autotoolstoolchain.html  it's managed automatically.


> Also if the shared option exists it will add by default:
> 
>         --enable-shared, --disable-static if shared==True
>         --disable-shared, --enable-static if shared==False

File: recipes/mpc/all/conanfile.py [hunk 3]
```diff
@@ -16,65 +23,78 @@ class MpcConan(ConanFile):
...
+            autotools.autoreconf(["-i"])
+        autotools.configure()
         autotools.make()
 
     def package(self):
-        self.copy(pattern="COPYING.LESSER", dst="licenses", src=self._source_subfolder)
-        autotools = self._configure_autotools()
+        copy(self, "COPYING.LESSER", self.source_folder, os.path.join(self.package_folder, "licenses"), keep_path=False)
+        autotools = Autotools(self)
         autotools.install()
```
Comment (StellaSmith) [inline recipes/mpc/all/conanfile.py:90]:
```suggestion
        autotools = Autotools(self)
        autotools.install()
        fix_apple_shared_install_name(self)
```

File: recipes/mpc/all/conanfile.py [hunk 4]
```diff
@@ -1,11 +1,18 @@
-from conans import ConanFile, AutoToolsBuildEnvironment, tools
-from conans.errors import ConanInvalidConfiguration
+from conan import ConanFile
+from conan.tools.env import VirtualBuildEnv
+from conan.tools.files import copy, get, rmdir, rm, apply_conandata_patches
+from conan.tools.layout import basic_layout
+from conan.tools.gnu import Autotools, AutotoolsToolchain, AutotoolsDeps
+from conan.tools.microsoft import is_msvc, unix_path
```
Comment (StellaSmith) [inline recipes/mpc/all/conanfile.py:6]:
```suggestion
from conan.tools.microsoft import is_msvc, unix_path
from conan.tools.apple import fix_apple_shared_install_name
```

**Review by StellaSmith — COMMENTED** [review]
https://docs.conan.io/en/2.0/reference/tools/apple/other.html#conan-tools-apple-fix-apple-shared-install-name

File: recipes/mpc/all/conanfile.py (hunk 1 above)
Comment (System-Arch) [reply recipes/mpc/all/conanfile.py]: Updated as suggested

File: recipes/mpc/all/conanfile.py (hunk 2 above)
Comment (System-Arch) [reply recipes/mpc/all/conanfile.py]: Removed if/else clause as suggested.

**Review by StellaSmith — DISMISSED** [review]

File: recipes/mpc/all/conanfile.py [hunk 5]
```diff
@@ -16,65 +24,75 @@ class MpcConan(ConanFile):
...
-        tools.remove_files_by_mask(os.path.join(self.package_folder, "lib"), "*.la")
+        fix_apple_shared_install_name(self)
+        rmdir(self, os.path.join(self.package_folder, "share"))
+        rm(self, "*.la", os.path.join(self.package_folder, "lib"), recursive=True)
 
     def package_info(self):
+        self.cpp_info.set_property("cmake_find_mode", "both")
+        self.cpp_info.set_property("cmake_file_name", "MPC")
+        self.cpp_info.set_property("cmake_module_file_name", "mpc")
+        self.cpp_info.set_property("cmake_target_name", "MPC::MPC")
```
Comment (SpaceIm) [inline recipes/mpc/all/conanfile.py:96]:
```suggestion
```

File: recipes/mpc/all/conanfile.py [hunk 6]
```diff
@@ -1,11 +1,19 @@
...
+from conan.tools.layout import basic_layout
+from conan.tools.gnu import Autotools, AutotoolsToolchain, AutotoolsDeps
+from conan.tools.microsoft import is_msvc, unix_path
+from conan.tools.apple import fix_apple_shared_install_name
+from conan.errors import ConanInvalidConfiguration
 import os
 
-required_conan_version = ">=1.33.0"
+
+required_conan_version = ">=1.56.0"
```
Comment (SpaceIm) [inline recipes/mpc/all/conanfile.py:12]:
```suggestion
required_conan_version = ">=1.54.0"
```

File: recipes/mpc/all/conanfile.py [hunk 7]
```diff
@@ -1,11 +1,19 @@
-from conans import ConanFile, AutoToolsBuildEnvironment, tools
-from conans.errors import ConanInvalidConfiguration
+from conan import ConanFile
+from conan.tools.env import VirtualBuildEnv
```
Comment (SpaceIm) [inline recipes/mpc/all/conanfile.py:2]:
```suggestion
from conan.tools.build import cross_building
from conan.tools.env import VirtualBuildEnv, VirtualRunEnv
```

File: recipes/mpc/all/conanfile.py [hunk 8]
```diff
@@ -16,65 +24,75 @@ class MpcConan(ConanFile):
...
-        args = []
-        if self.options.shared:
-            args.extend(["--disable-static", "--enable-shared"])
-        else:
-            args.extend(["--disable-shared", "--enable-static"])
-        self._autotools.configure(args=args, configure_dir=self._source_subfolder)
-        return self._autotools
+    def generate(self):
+        env = VirtualBuildEnv(self)
+        env.generate()
```
Comment (SpaceIm) [inline recipes/mpc/all/conanfile.py:66]:
```suggestion
        env.generate()
        if not cross_building(self):
            env = VirtualRunEnv(self)
            env.generate(scope="build")
```

**Review by SpaceIm — CHANGES_REQUESTED** [review]
Inject VirtualRunEnv in build scope for native build, otherwise configure step of autotools on Linux & Windows will break if dependencies are shared

File: recipes/mpc/all/conanfile.py [hunk 9]
```diff
@@ -1,11 +1,19 @@
-from conans import ConanFile, AutoToolsBuildEnvironment, tools
-from conans.errors import ConanInvalidConfiguration
+from conan import ConanFile
+from conan.tools.env import VirtualBuildEnv
+from conan.tools.files import copy, get, rmdir, rm, apply_conandata_patches
```
Comment (SpaceIm) [inline recipes/mpc/all/conanfile.py:3]:
```suggestion
from conan.tools.files import apply_conandata_patches, copy, export_conandata_patches, get, rm, rmdir
```

File: recipes/mpc/all/conanfile.py [hunk 10]
```diff
@@ -16,65 +24,75 @@ class MpcConan(ConanFile):
     options = {"shared": [True, False], "fPIC": [True, False]}
     default_options = {"shared": False, "fPIC": True}
     exports_sources = "patches/**"
```
Comment (SpaceIm) [inline recipes/mpc/all/conanfile.py:26]:
```suggestion

    def export_sources(self):
        export_conandata_patches(self)
```

**Review by SpaceIm — CHANGES_REQUESTED** [review]

File: recipes/mpc/all/conanfile.py [hunk 11]
```diff
@@ -16,65 +24,75 @@ class MpcConan(ConanFile):
...
+        tc.generate()
 
     def build(self):
-        for patch in self.conan_data.get("patches", {}).get(self.version, []):
-            tools.patch(**patch)
-        autotools = self._configure_autotools()
+        apply_conandata_patches(self)
+        autotools = Autotools(self)
+        if not os.path.exists(os.path.join(self.source_folder, "configure")):
+            autotools.autoreconf(["-i"])
```
Comment (SpaceIm) [inline recipes/mpc/all/conanfile.py:80]:
```suggestion
```

File: recipes/mpc/all/conanfile.py [hunk 12]
```diff
@@ -16,65 +24,75 @@ class MpcConan(ConanFile):
...
+        rmdir(self, os.path.join(self.package_folder, "share"))
+        rm(self, "*.la", os.path.join(self.package_folder, "lib"), recursive=True)
 
     def package_info(self):
+        self.cpp_info.set_property("cmake_find_mode", "both")
+        self.cpp_info.set_property("cmake_file_name", "MPC")
+        self.cpp_info.set_property("cmake_module_file_name", "mpc")
+        self.cpp_info.set_property("cmake_target_name", "MPC::MPC")
         self.cpp_info.libs = ["mpc"]
+        self.cpp_info.system_libs = ["m"]
```
Comment (SpaceIm) [inline recipes/mpc/all/conanfile.py:98]:
```suggestion
        if self.settings.os in ["Linux", "FreeBSD"]:
            self.cpp_info.system_libs = ["m"]
```

File: recipes/mpc/all/test_package/CMakeLists.txt [hunk 13]
```diff
@@ -1,8 +1,7 @@
 cmake_minimum_required(VERSION 3.1)
 project(test_package C)
 
-include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
-conan_basic_setup()
+find_package(MPC REQUIRED CONFIG)
```
Comment (SpaceIm) [inline recipes/mpc/all/test_package/CMakeLists.txt:4]:
```suggestion
find_package(mpc REQUIRED CONFIG)
```

File: recipes/mpc/all/test_package/CMakeLists.txt [hunk 14]
```diff
@@ -1,8 +1,7 @@
...
 
 add_executable(${PROJECT_NAME} test_package.c)
-target_link_libraries(${PROJECT_NAME} ${CONAN_LIBS})
+target_link_libraries(${PROJECT_NAME} PRIVATE MPC::MPC)
```
Comment (SpaceIm) [inline recipes/mpc/all/test_package/CMakeLists.txt:7]:
```suggestion
target_link_libraries(${PROJECT_NAME} PRIVATE mpc::mpc)
```

File: recipes/mpc/all/test_v1_package/conanfile.py [hunk 15]
```diff
@@ -0,0 +1,17 @@
...
+
+    def build(self):
+        cmake = CMake(self)
+        cmake.configure()
+        cmake.build()
+
+    def test(self):
+        if not tools.cross_building(self.settings):
+            bin_path = os.path.join("bin", "test_package")
+            self.run(bin_path, run_environment=True)
```
Comment (SpaceIm) [inline recipes/mpc/all/test_v1_package/conanfile.py:17]:
```suggestion
cmake_minimum_required(VERSION 3.1)
project(test_package)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)

add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../test_package
                 ${CMAKE_CURRENT_BINARY_DIR}/test_package)
```

File: recipes/mpc/all/test_v1_package/CMakeLists.txt [hunk 16]
```diff
@@ -0,0 +1,8 @@
+cmake_minimum_required(VERSION 3.1)
+project(test_package C)
+
+include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
+conan_basic_setup()
+
+add_executable(${PROJECT_NAME} test_package.c)
+target_link_libraries(${PROJECT_NAME} ${CONAN_LIBS})
```
Comment (SpaceIm) [inline recipes/mpc/all/test_v1_package/CMakeLists.txt:8]:
```suggestion
cmake_minimum_required(VERSION 3.1)
project(test_package)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)

add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../test_package
                 ${CMAKE_CURRENT_BINARY_DIR}/test_package)
```

File: recipes/mpc/all/test_v1_package/conanfile.py [hunk 17]
```diff
@@ -0,0 +1,17 @@
+from conans import ConanFile, CMake, tools
+import os
+
+
+class TestPackageConan(ConanFile):
+    settings = "os", "compiler", "build_type", "arch"
+    generators = "cmake"
```
Comment (SpaceIm) [inline recipes/mpc/all/test_v1_package/conanfile.py:7]:
```suggestion
    generators = "cmake", "cmake_find_package_multi"
```

File: recipes/mpc/all/test_v1_package/test_package.c [hunk 18]
```diff
@@ -0,0 +1,16 @@
+/* example was taken from https://www.gnu.org/ghm/2011/paris/slides/andreas-enge-mpc.pdf */
```
Comment (SpaceIm) [inline recipes/mpc/all/test_v1_package/test_package.c:1]: no code duplication please.

**Review by SpaceIm — CHANGES_REQUESTED** [review]

File: recipes/mpc/all/test_v1_package/test_package.c (hunk 18 above)
Comment (System-Arch) [reply recipes/mpc/all/test_v1_package/test_package.c]: Deleted file per request.

**Review by uilianries — APPROVED** [review]
LGTM

**Review by StellaSmith — APPROVED** [review]

**Review by prince-chrismc — APPROVED** [review]
