### ISSUE TITLE
[package] libsystemd/255.10: Unable to build with glibc-2.43

### ISSUE THREAD

**Issue by AnatoliiShablov** [conan-io/conan-center-index#30420]
### Description

Unable to compile this recipe because there were added new errno in kernel headers. There is fix in libsystemd repo already, maybe we can add patch to recipe too?

https://github.com/systemd/systemd/commit/3cfb16998808a6ec8012a6120d0a82f0e1a0c8bb

Also the same on embedded forums

 https://lists.openembedded.org/g/openembedded-core/topic/whinlatter_patch_7_7/118580471

### Package and Environment Details

* Package Name/Version: **libsystemd/255.10**
* Operating System+version: **Linux OpenSUSE Tumbleweed**
* Compiler+version: **GCC 15.2**
* Conan version: **2.28.1**
* Python version: **Python 3.13.13**

### Conan profile

[settings]
arch=x86_64
build_type=RelWithDebInfo
compiler=gcc
compiler.cppstd=20
compiler.cstd=gnu23
compiler.libcxx=libstdc++11
compiler.version=15
os=Linux
[conf]
tools.build:compiler_executables={'c': 'gcc', 'cpp': 'g++'}

### Steps to reproduce

`conan install --requires=libsystemd/255.10 --build=missing`

### Logs

<details><summary>Click to expand log</summary>

```
src/basic/errno-to-name.h:71:23: error: initialized field overwritten [-Werror=override-init]
   71 |         [EFSBADCRC] = "EFSBADCRC",
      |                       ^~~~~~~~~~~
src/basic/errno-to-name.h:71:23: note: (near initialization for ?errno_names[74]?)
src/basic/errno-to-name.h:114:26: error: initialized field overwritten [-Werror=override-init]
  114 |         [EFSCORRUPTED] = "EFSCORRUPTED",
```

</details>
