### PR TITLE
Troubleshooting 'sdl_mixer: conan v2 support' PR

### PR DESCRIPTION
**Pull request by ssrobins**
This is not intended to merge, I'm just trying to help with https://github.com/conan-io/conan-center-index/pull/18836 by attempting to solve the CI failures it has.

### CODE REVIEW

**Comment by ssrobins** [comment]
I found the problem causing the v2 test failure. The `*_DYNAMIC` preprocessor defines like `FLAC_DYNAMIC` are just being defined:
```
add_definitions("-D${type}_DYNAMIC")
```

But the `SDL_LoadObject` function that uses it is expecting it to be defined to a string corresponding to the shared library name:
```
#ifdef FLAC_DYNAMIC
        flac.handle = SDL_LoadObject(FLAC_DYNAMIC);
        if (flac.handle == NULL) {
            return -1;
        }
```

In newer versions of SDL_mixer, an official CMakeLists.txt was added and you can see that's exactly what it's doing:
https://github.com/libsdl-org/SDL_mixer/blob/08c0ad55ca79498a899534cf874eae6d867bf043/CMakeLists.txt#L600

Removing the `*_DYNAMIC` defines works around the problem because the `#ifdef` prevents it from getting to the `SDL_LoadObject`` call. The output from the test_package run still indicates support for several of the audio formats, including FLAC:
```
sdl_mixer/2.0.4 (test package): RUN: ./test_package
SDL2_mixer version: 2.0.4
Supported MIX_INIT_MOD:  Yes
Supported MIX_INIT_MP3:  Yes
Supported MIX_INIT_OGG:  Yes
Supported MIX_INIT_FLAC:  Yes
Supported MIX_INIT_MID:  No
Supported MIX_INIT_OPUS:  Yes
```

I think that's because the explicit load isn't necessary since the SDL_mixer shared library is built with the dependencies and has all the rpath settings to find the .so files so everything loads automatically at startup.

**Comment by ssrobins** [comment]
As for the windows build error:

```
Creating library C:/J/w/prod/BuildSingleReference/.conan/data/sdl_mixer/2.0.4/_/_/build/d7d69c930b152bee9cb71865c7ad680243ef7c19/build/Release/SDL2_mixer.lib and object C:/J/w/prod/BuildSingleReference/.conan/data/sdl_mixer/2.0.4/_/_/build/d7d69c930b152bee9cb71865c7ad680243ef7c19/build/Release/SDL2_mixer.exp
music_flac.obj : error LNK2019: unresolved external symbol __imp_FLAC__stream_decoder_new referenced in function FLAC_Load [C:\J\w\prod\BuildSingleReference\.conan\data\sdl_mixer\2.0.4\_\_\build\d7d69c930b152bee9cb71865c7ad680243ef7c19\build\sdl2_mixer.vcxproj]
music_flac.obj : error LNK2019: unresolved external symbol __imp_FLAC__stream_decoder_delete referenced in function FLAC_Load [C:\J\w\prod\BuildSingleReference\.conan\data\sdl_mixer\2.0.4\_\_\build\d7d69c930b152bee9cb71865c7ad680243ef7c19\build\sdl2_mixer.vcxproj]
music_flac.obj : error LNK2019: unresolved external symbol __imp_FLAC__stream_decoder_get_state referenced in function FLAC_Load [C:\J\w\prod\BuildSingleReference\.conan\data\sdl_mixer\2.0.4\_\_\build\d7d69c930b152bee9cb71865c7ad680243ef7c19\build\sdl2_mixer.vcxproj]
music_flac.obj : error LNK2019: unresolved external symbol __imp_FLAC__stream_decoder_init_stream referenced in function FLAC_Load [C:\J\w\prod\BuildSingleReference\.conan\data\sdl_mixer\2.0.4\_\_\build\d7d69c930b152bee9cb71865c7ad680243ef7c19\build\sdl2_mixer.vcxproj]
music_flac.obj : error LNK2019: unresolved external symbol __imp_FLAC__stream_decoder_finish referenced in function FLAC_Load [C:\J\w\prod\BuildSingleReference\.conan\data\sdl_mixer\2.0.4\_\_\build\d7d69c930b152bee9cb71865c7ad680243ef7c19\build\sdl2_mixer.vcxproj]
music_flac.obj : error LNK2019: unresolved external symbol __imp_FLAC__stream_decoder_flush referenced in function FLAC_Load [C:\J\w\prod\BuildSingleReference\.conan\data\sdl_mixer\2.0.4\_\_\build\d7d69c930b152bee9cb71865c7ad680243ef7c19\build\sdl2_mixer.vcxproj]
music_flac.obj : error LNK2019: unresolved external symbol __imp_FLAC__stream_decoder_process_single referenced in function FLAC_Load [C:\J\w\prod\BuildSingleReference\.conan\data\sdl_mixer\2.0.4\_\_\build\d7d69c930b152bee9cb71865c7ad680243ef7c19\build\sdl2_mixer.vcxproj]
music_flac.obj : error LNK2019: unresolved external symbol __imp_FLAC__stream_decoder_process_until_end_of_metadata referenced in function FLAC_Load [C:\J\w\prod\BuildSingleReference\.conan\data\sdl_mixer\2.0.4\_\_\build\d7d69c930b152bee9cb71865c7ad680243ef7c19\build\sdl2_mixer.vcxproj]
music_flac.obj : error LNK2019: unresolved external symbol __imp_FLAC__stream_decoder_process_until_end_of_stream referenced in function FLAC_Load [C:\J\w\prod\BuildSingleReference\.conan\data\sdl_mixer\2.0.4\_\_\build\d7d69c930b152bee9cb71865c7ad680243ef7c19\build\sdl2_mixer.vcxproj]
music_flac.obj : error LNK2019: unresolved external symbol __imp_FLAC__stream_decoder_seek_absolute referenced in function FLAC_Load [C:\J\w\prod\BuildSingleReference\.conan\data\sdl_mixer\2.0.4\_\_\build\d7d69c930b152bee9cb71865c7ad680243ef7c19\build\sdl2_mixer.vcxproj]
C:\J\w\prod\BuildSingleReference\.conan\data\sdl_mixer\2.0.4\_\_\build\d7d69c930b152bee9cb71865c7ad680243ef7c19\build\Release\SDL2_mixer.dll : fatal error LNK1120: 10 unresolved externals [C:\J\w\prod\BuildSingleReference\.conan\data\sdl_mixer\2.0.4\_\_\build\d7d69c930b152bee9cb71865c7ad680243ef7c19\build\sdl2_mixer.vcxproj]
```

It works fine with flac 1.3.3, but fails with flac 1.4.2. We can't just downgrade, because that causes version conflicts on Linux dependencies.

Using MSVC's `dumpbin` tool, I can confirm that symbol is present in `FLAC.lib` and that the library is static as expected. I see no difference between the two versions of flac that would explain this...
