### ISSUE TITLE
[package] autoconf/2.71 does not work with Conan 2.0

### ISSUE THREAD

**Issue by System-Arch** [conan-io/conan-center-index#14860]
### Description

The autoconf recipe was nominally ported to Conan 2.0 but had an incompatible workaround for https://github.com/conan-io/conan/issues/12499. Now that the fix for that issue has been released with Conan, we can remove the workaround so that the recipe works with Conan 2.0

### Package and Environment Details

Package Name/Version: autoconf/2,71
Operating System+version: Debian 10
Compiler+version: gcc 8
Conan version: conan 2.0.0-beta6
Python version: Python 3.7.3

### Conan profile

Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
[options]
cmake*:bootstrap=True
[tool_requires]
!openssl*: cmake/3.24.2

### Steps to reproduce

conan-2.0 source --name autoconf --version 2.71 .

### Logs

<details><summary>Click to expand log</summary>

```
conan-2.0 source --name autoconf --version 2.71 .
ERROR: Error loading conanfile at '/tmp/tmp.5VWf08gJrQ/autoconf/conanfile.py': Unable to load conanfile in /tmp/tmp.5VWf08gJrQ/autoconf/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmp.5VWf08gJrQ/autoconf/conanfile.py", line 7, in <module>
    from conans import tools as tools_legacy
ImportError: cannot import name 'tools' from 'conans' (/mathworks/devel/sandbox/marc/conan-2.0/conan-io/conans/__init__.py)```

</details>

**Comment by System-Arch** [comment]
I will submit a fix shortly.

**Comment by SpaceIm** [comment]
The fix you refer on has been released in conan 1.55.0, but c3i runs conan 1.54.0

**Comment by RubenRBS** [comment]
Woops, sorry that we didn't give you a heads-up sooner, but autoconf has now been ported for a bit, let us know if you find any problems with it :)
