### PR TITLE
add keychain/1.2.1

### PR DESCRIPTION
**Pull request by hrantzsch**
Specify library name and version:  **keychain/1.2.1**

- Update to version 1.2.1. Not conan2 ready, though
- Remove topic "conan"

---

- [x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by hrantzsch** [comment]
I don't understand the error from the v1 pipeline. It seems to think I changed another recipe as well (twice)?

**Comment by hrantzsch** [comment]
Hmm, I cannot figure out what the error is. And was it stuck for a whole week now before reporting the error?

It seems the existing 1.2.0 fails on Linux, GCC. It doesn't show me why though.

Any tips? Perhaps @prince-chrismc?

**Comment by prince-chrismc** [comment]
The server was restarted and reran all PRs it's complete separate from the previous failure

**Comment by prince-chrismc** [comment]
You need to update the imports for the pull request to be accepted.
If you push a new commit it should be able to build

File: recipes/keychain/all/conanfile.py [hunk 1]
```diff
@@ -1,26 +1,27 @@
...
     homepage = "https://github.com/hrantzsch/keychain"
     description = "A cross-platform wrapper for the operating system's credential storage"
-    topics = ("conan", "keychain", "security", "credentials", "password", "cpp11")
+    topics = ("keychain", "security", "credentials", "password", "cpp11")
     url = "https://github.com/conan-io/conan-center-index"
     license = "MIT"
     settings = "os", "arch", "compiler", "build_type"
     exports_sources = ["CMakeLists.txt"]
-    generators = "cmake", "pkg_config"
     options = {'fPIC': [False, True]}
```
Comment (jcar87) [inline recipes/keychain/all/conanfile.py:19]: The missing binaries are an interesting consequence of `dlib` having a `shared=True` default while all others have `shared=False` by default - for Conan 2.0, the CI pipeline no longer builds those configurations and will enforce either all shared or all static.

This would be fixed if this library had the `shared` option - does this library support it? is there a reason why it shouldn't be an option?

Comment (hrantzsch) [reply recipes/keychain/all/conanfile.py]: There is not! I added the option to the recipe.

This revealed that the test package has to be adjusted to conan2 as well. I did that but without the old `conan_basic_setup()` magic I cannot get it to link to the dependencies anymore. I'm very much stuck and would greatly appreciate a hint.

**Comment by hrantzsch** [comment]
Hi @jcar87, thanks for picking this up and trying to fix it. I've also given it another try based on your commit.

While I still don't understand why libsecret apparently fails to link to gio, I think keychain should maybe explicitly declare its own dependency to gio. I tried this:

```diff
diff --git a/recipes/keychain/all/conanfile.py b/recipes/keychain/all/conanfile.py
index 640dda688..15c3fc3a2 100644
--- a/recipes/keychain/all/conanfile.py
+++ b/recipes/keychain/all/conanfile.py
@@ -1,4 +1,5 @@
 from conan import ConanFile
+from conan.tools.build import can_run
 from conan.tools.build import check_min_cppstd
 from conan.tools.cmake import CMake, CMakeToolchain, cmake_layout
 from conan.tools.files import collect_libs, copy, get
@@ -34,7 +35,8 @@ class KeychainConan(ConanFile):
 
     def requirements(self):
         if self.settings.os == "Linux":
-            self.requires("libsecret/0.20.4")
+            self.requires("glib/2.76.0", transitive_headers=True, transitive_libs=True, run=can_run(self))
+            self.requires("libsecret/0.20.5")
 
     def build_requirements(self):
         if self.settings.os == "Linux":
```

However, this only results in linker errors in libgio: 
```
/usr/bin/ld: /home/hannes/.conan2/p/glib68020c5036aa3/p/lib/libgio-2.0.a(gthreadedresolver.c.o): in function `g_resolver_records_from_res_query':
gthreadedresolver.c:(.text+0xf73): undefined reference to `__dn_expand'
/usr/bin/ld: gthreadedresolver.c:(.text+0x101f): undefined reference to `__dn_expand'
```

The internet says `-lresolv` fixes this issue for others, but `-lresolv` is already there and in addition, `libresolv.a` on my system doesn't contain that symbol (only `U __libc_dn_expand`).

I'm out of ideas again. Have you encountered a similar problem?

**Comment by jcar87** [comment]
Hi @hrantzsch  - interesting problem! From what I can see, Keychain itself seachers for and links against glib, so you're on the right track about this being a dependency that should be expressed directly in the recipe.

Adding `self.requires("glib/2.76.0")` should work on its own - are you certain that the trainsitive traits are required? I'll push this small change for now and evaluate from there :) 

I wonder if we are also affected by this:  https://github.com/conan-io/conan-center-index/pull/17502

**Comment by hrantzsch** [comment]
You're right, the transitive traits should not be needed. I copied it blindly from libsecret...
In any case, it works now, at least on my arch installation :tada: 
On my Ubuntu it only works if I specify `-o "*:shared=True"`, but I suspect this is caused by some files still lying around from previous attempts.

**Comment by jcar87** [comment]
I've pushed a fix in the `test_package` such that the CMakeLists uses c++11 (or higher if the cppstd setting is defined) - the error in gcc5 is caused by `enum class` being C++11. I believe this should fix the Conan 1.x test package issues.

I've also removed the previously exported `CMakeLists.txt`, which is no longer in use after the Conan 2.0 migration.

I'm looking into the missing dependencies in Conan 2.0

**Comment by jcar87** [comment]
> You're right, the transitive traits should not be needed. I copied it blindly from libsecret... In any case, it works now, at least on my arch installation 🎉 On my Ubuntu it only works if I specify `-o "*:shared=True"`, but I suspect this is caused by some files still lying around from previous attempts.

Glad to hear this works!  I suspect the `*:shared=True` being needed could be caused by an outdated _revision_ of the `glib` recipe

**Comment by jcar87** [comment]
@hrantzsch, I've added a definition of `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` to `True`, otherwise on Windows with msvc no shared library will be generated as there are no exported symbols (unlike Unix platforms, on Windows symbols need to be explicitly "exported" with symbol specifiers). If you think that as library author this is not intended or supported, the alternative would be to invalidate the `shared=True` variant on Windows.

**Review by jcar87 — APPROVED** [review]

**Review by RubenRBS — APPROVED** [review]

**Comment by jcar87** [comment]
> Huge thanks for making this work, @jcar87! Regarding `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`, I don't see anything that would speak against it.

No worries, thank you for your contribution!! In the end we got there :)
